VideoCapture Class Reference | ZED Open Capture API Reference | Stereolabs
VideoCapture Class Reference
The VideoCapture class provides image grabbing functions and settings control for all the Stereolabs camera models.
Functions
VideoCapture (VideoParams params=VideoParams())
The default constructor.
virtual ~VideoCapture ()
The class destructor.
bool initializeVideo (int devId=-1)
Open a ZED camera using the specified ID or searching for the first available.
const Frame * getLastFrame (uint64_t timeout_msec=10)
Get the last received camera image.
void getFrameSize (int &width, int &height)
Get the size of the camera frame.
int setLEDstatus (bool status)
Set the status of the camera led.
int getLEDstatus (bool *status)
Get the status of the camera led.
int toggleLED (bool *value)
Toggle the status of the camera led.
void setBrightness (int brightness)
Set the Brightness value.
int getBrightness ()
Get the Brightness value.
void resetBrightness ()
Reset the Brightness value to default value.
void setSharpness (int sharpness)
Set the Sharpness value.
int getSharpness ()
Get the Sharpness value.
void resetSharpness ()
Reset the Sharpness value to default value.
void setContrast (int contrast)
Set the Contrast value.
int getContrast ()
Get the Contrast value.
void resetContrast ()
Reset the Contrast value to default value.
void setHue (int hue)
Set the Hue value.
int getHue ()
Get the Hue value.
void resetHue ()
Reset the Hue value to default value.
void setSaturation (int saturation)
Set the Saturation value.
int getSaturation ()
Get the Saturation value.
void resetSaturation ()
Reset the Saturation value to default value.
void setWhiteBalance (int wb)
Set the White Balance value (disable auto White Balance if active)
int getWhiteBalance ()
Get the White Balance value.
void setAutoWhiteBalance (bool active)
Enable/Disable the automatic White Balance control.
bool getAutoWhiteBalance ()
Get the status of the automatic White Balance control.
void resetAutoWhiteBalance ()
Reset the automatic White Balance control value to default value.
void setGamma (int gamma)
Set the Gamma value.
int getGamma ()
Get the Gamma value.
void resetGamma ()
Reset the Gamma value to default value.
int setAECAGC (bool active)
Enable/Disable the automatic Exposure and Gain control.
bool getAECAGC ()
Get the status of the automatic Exposure and Gain control.
void resetAECAGC ()
Reset the automatic Exposure and Gain control value to default value.
void setGain (CAM_SENS_POS cam, int gain)
Set the Gain value (disable Exposure and Gain control if active)
int getGain (CAM_SENS_POS cam)
Get the current Gain value.
void setExposure (CAM_SENS_POS cam, int exposure)
Set the Exposure value (disable Exposure and Gain control if active)
int getExposure (CAM_SENS_POS cam)
Get the current Exposure value.
int getSerialNumber ()
Retrieve the serial number of the connected camera.
bool enableSensorSync (SensorCapture *sensCap=nullptr)
Enable synchronizations between Camera frame and Sensors timestamps.
void setReadyToSync ()
Indicates that the SensorCapture object received the HW sync signal and a frame must be synchronized to the last Sensor Data.
Detailed Description
The VideoCapture class provides image grabbing functions and settings control for all the Stereolabs camera models.
Examples
zed_oc_rectify_example.cpp, zed_oc_sync_example.cpp, and zed_oc_video_example.cpp.
Definition at line 53 of file videocapture.hpp.
Constructor and Destructor
VideoCapture()
VideoCapture (VideoParams params = VideoParams())
The default constructor.
Parameters
params the initialization parameters (see VideoParams)
Definition at line 113 of file videocapture.cpp.
 {
     memcpy( &mParams, &params, sizeof(VideoParams) );
     if( mParams.verbose )
     {
         std::string ver =
                 "ZED Open Capture - Camera module - Version: "
                 + std::to_string(mMajorVer) + "."
                 + std::to_string(mMinorVer) + "."
                 + std::to_string(mPatchVer);
         INFO_OUT(mParams.verbose,ver);
     }
     // Check that FPS is coherent with user resolution
     checkResFps( );
     // Calculate gain zones (required because the raw gain control is not continuous in the range of values)
     mGainSegMax = (GAIN_ZONE4_MAX-GAIN_ZONE4_MIN)+(GAIN_ZONE3_MAX-GAIN_ZONE3_MIN)+(GAIN_ZONE2_MAX-GAIN_ZONE2_MIN)+(GAIN_ZONE1_MAX-GAIN_ZONE1_MIN);
     // FPS mapping
     if( mFps <= 15 )
         mExpoureRawMax = EXP_RAW_MAX_15FPS;
     else if( mFps <= 30 )
         mExpoureRawMax = EXP_RAW_MAX_30FPS;
     else if( mFps <= 60 )
         mExpoureRawMax = EXP_RAW_MAX_60FPS;
     else
         mExpoureRawMax = EXP_RAW_MAX_100FPS;
 }
References VideoParams::verbose.
~VideoCapture()
~VideoCapture () virtual
The class destructor.
Definition at line 144 of file videocapture.cpp.
 {
     reset();
 }
Functions
initializeVideo()
bool initializeVideo (int devId = -1)
Open a ZED camera using the specified ID or searching for the first available.
Parameters
devId Id of the camera (see /dev/video*). Use -1 to open the first available camera
Returns
returns true if the camera is correctly opened
Examples
zed_oc_video_example.cpp.
Definition at line 274 of file videocapture.cpp.
 {
     reset();
     bool opened=false;
     if( devId==-1 )
     {
         // Try to open all the devices until the first success (max allowed by v4l: 64)
         for( uint8_t id=0; id<64; id++ )
         {
             opened = openCamera( id );
             if(opened) break;
         }
     }
     else
     {
         opened = openCamera( static_cast<uint8_t>(devId) );
     }
     if(!opened)
     {
         return false;
     }
     mInitialized = startCapture();
     if( mParams.verbose && mInitialized)
     {
         std::string msg = "Device '" + mDevName + "' opened";
         INFO_OUT(mParams.verbose,msg );
     }
     setLEDstatus( true );
     resetAECAGC();
     resetAutoWhiteBalance();
     resetBrightness();
     resetContrast();
     resetGamma();
     resetHue();
     resetSaturation();
     resetSharpness();
     return mInitialized;
 }
References VideoCapture::resetAECAGC(), VideoCapture::resetAutoWhiteBalance(), VideoCapture::resetBrightness(), VideoCapture::resetContrast(), VideoCapture::resetGamma(), VideoCapture::resetHue(), VideoCapture::resetSaturation(), VideoCapture::resetSharpness(), VideoCapture::setLEDstatus(), and VideoParams::verbose.
getLastFrame()
const Frame * getLastFrame (uint64_t timeout_msec = 10)
Get the last received camera image.
Parameters
timeout_msec frame grabbing timeout in millisecond.
Returns
returns the last received frame as pointer.
Note
Do not delete the received frame
Frame received will contains the RAW buffer from the camera, in YUV4:2:2 color format and in side by side mode. Images must then be converted to RGB for proper display and will not be rectified.
Examples
zed_oc_video_example.cpp.
Definition at line 858 of file videocapture.cpp.
 {
     // ----> Wait for a new frame
     uint64_t time_count = timeout_msec*10;
     while( !mNewFrame )
     {
         if(time_count==0)
         {
             return nullptr;
         }
         time_count--;
         usleep(100);
     }
     // <---- Wait for a new frame
     // Get the frame mutex
     const std::lock_guard<std::mutex> lock(mBufMutex);
     mNewFrame = false;
     return &mLastFrame;
 }
getFrameSize()
void getFrameSize (int & width, int & height) inline
Get the size of the camera frame.
Parameters
width the frame width
height the frame height
Definition at line 92 of file videocapture.hpp.
 {width=mWidth;height=mHeight;}
setLEDstatus()
int setLEDstatus (bool status)
Set the status of the camera led.
Parameters
status true for "ON", false for "OFF"
Returns
returns a negative value if an error occurred
Definition at line 1357 of file videocapture.cpp.
 {
     int hr = 0;
     //LED GPIO : GPIO 2
     if (status) {
         hr += ll_set_gpio_direction(2, 0);
         hr += ll_set_gpio_value(2, 1);
     } else {
         hr += ll_set_gpio_direction(2, 0);
         hr += ll_set_gpio_value(2, 0);
     }
     return hr;
 }
Referenced by VideoCapture::initializeVideo(), and VideoCapture::toggleLED().
getLEDstatus()
int getLEDstatus (bool * status)
Get the status of the camera led.
Parameters
value returned status: true for "ON", false for "OFF"
Returns
returns a negative value if an error occurred
Definition at line 1372 of file videocapture.cpp.
 {
     if( status==nullptr)
     {
         return -1;
     }
     uint8_t val;
     int hr = ll_set_gpio_direction(2, 1);
     hr += ll_get_gpio_value(2, &val);
     *status = val!=0;
     return hr;
 }
Referenced by VideoCapture::toggleLED().
toggleLED()
int toggleLED (bool * value)
Toggle the status of the camera led.
Parameters
value returned status: true for "ON", false for "OFF"
Returns
returns a negative value if an error occurred
Definition at line 1386 of file videocapture.cpp.
 {
     bool curVal;
     int ret = getLEDstatus( &curVal );
     if(ret==0)
     {
         bool newVal = !curVal;
         ret = setLEDstatus( newVal );
         if( ret==0 && value!=nullptr )
         {
             *value = newVal;
         }
     }
     return ret;
 }
References VideoCapture::getLEDstatus(), and VideoCapture::setLEDstatus().
setBrightness()
void setBrightness (int brightness)
Set the Brightness value.
Parameters
brightness Brightness value in the range [0,8]
Definition at line 1526 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_BRIGHTNESS, brightness);
 }
getBrightness()
int getBrightness ()
Get the Brightness value.
Returns
the current Brightness value
Definition at line 1536 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_BRIGHTNESS);
 }
resetBrightness()
void resetBrightness ()
Reset the Brightness value to default value.
Definition at line 1531 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_BRIGHTNESS);
 }
Referenced by VideoCapture::initializeVideo().
setSharpness()
void setSharpness (int sharpness)
Set the Sharpness value.
Parameters
sharpness Sharpness value in the range [0,8]
Definition at line 1541 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_SHARPNESS, sharpness);
 }
getSharpness()
int getSharpness ()
Get the Sharpness value.
Returns
the current Sharpness value
Definition at line 1551 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_SHARPNESS);
 }
resetSharpness()
void resetSharpness ()
Reset the Sharpness value to default value.
Definition at line 1546 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_SHARPNESS);
 }
Referenced by VideoCapture::initializeVideo().
setContrast()
void setContrast (int contrast)
Set the Contrast value.
Parameters
contrast Contrast value in the range [0,8]
Definition at line 1556 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_CONTRAST, contrast);
 }
getContrast()
int getContrast ()
Get the Contrast value.
Returns
the current Contrast value
Definition at line 1566 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_CONTRAST);
 }
resetContrast()
void resetContrast ()
Reset the Contrast value to default value.
Definition at line 1561 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_CONTRAST);
 }
Referenced by VideoCapture::initializeVideo().
setHue()
void setHue (int hue)
Set the Hue value.
Parameters
hue Hue value in the range [0,11]
Definition at line 1571 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_HUE, hue);
 }
getHue()
int getHue ()
Get the Hue value.
Returns
the current Hue value
Definition at line 1581 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_HUE);
 }
resetHue()
void resetHue ()
Reset the Hue value to default value.
Definition at line 1576 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_HUE);
 }
Referenced by VideoCapture::initializeVideo().
setSaturation()
void setSaturation (int saturation)
Set the Saturation value.
Parameters
saturation Saturation value in the range [0,8]
Definition at line 1586 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_SATURATION, saturation);
 }
getSaturation()
int getSaturation ()
Get the Saturation value.
Returns
the current Saturation value
Definition at line 1596 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_SATURATION);
 }
resetSaturation()
void resetSaturation ()
Reset the Saturation value to default value.
Definition at line 1591 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_SATURATION);
 }
Referenced by VideoCapture::initializeVideo().
setWhiteBalance()
void setWhiteBalance (int wb)
Set the White Balance value (disable auto White Balance if active)
Parameters
wb White Balance value in the range [2800,6500]
Definition at line 1606 of file videocapture.cpp.
 {
     // Disable auto white balance if active
     if (getAutoWhiteBalance() != 0)
         setAutoWhiteBalance(false);
     setCameraControlSettings(LINUX_CTRL_AWB, wb);
 }
References VideoCapture::getAutoWhiteBalance(), and VideoCapture::setAutoWhiteBalance().
getWhiteBalance()
int getWhiteBalance ()
Get the White Balance value.
Returns
the current White Balance value
Definition at line 1601 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_AWB);
 }
setAutoWhiteBalance()
void setAutoWhiteBalance (bool active)
Enable/Disable the automatic White Balance control.
Parameters
active true to activate automatic White Balance
Definition at line 1620 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_AWB_AUTO, active?1:0);
 }
Referenced by VideoCapture::resetAutoWhiteBalance(), and VideoCapture::setWhiteBalance().
getAutoWhiteBalance()
bool getAutoWhiteBalance ()
Get the status of the automatic White Balance control.
Returns
the status of the automatic White Balance control
Definition at line 1615 of file videocapture.cpp.
 {
     return (getCameraControlSettings(LINUX_CTRL_AWB_AUTO)!=0);
 }
Referenced by VideoCapture::setWhiteBalance().
resetAutoWhiteBalance()
void resetAutoWhiteBalance ()
Reset the automatic White Balance control value to default value.
Definition at line 1625 of file videocapture.cpp.
 {
     setAutoWhiteBalance(true);
 }
References VideoCapture::setAutoWhiteBalance().
Referenced by VideoCapture::initializeVideo().
setGamma()
void setGamma (int gamma)
Set the Gamma value.
Parameters
gamma Gamma value in the range [1,9]
Definition at line 1630 of file videocapture.cpp.
 {
     int current_gamma = getCameraControlSettings(LINUX_CTRL_GAMMA);
     if (gamma!=current_gamma)
     {
         setGammaPreset(0,gamma);
         setGammaPreset(1,gamma);
         setCameraControlSettings(LINUX_CTRL_GAMMA, gamma);
     }
 }
getGamma()
int getGamma ()
Get the Gamma value.
Returns
the current Gamma value
Definition at line 1650 of file videocapture.cpp.
{
     return getCameraControlSettings(LINUX_CTRL_GAMMA);
 }
resetGamma()
void resetGamma ()
Reset the Gamma value to default value.
Definition at line 1642 of file videocapture.cpp.
 {
     int def_value = DEFAULT_GAMMA_NOECT;
     setGammaPreset(0,def_value);
     setGammaPreset(1,def_value);
     setCameraControlSettings(LINUX_CTRL_GAMMA, def_value);
 }
Referenced by VideoCapture::initializeVideo().
setAECAGC()
int setAECAGC (bool active)
Enable/Disable the automatic Exposure and Gain control.
Parameters
active true to activate automatic White Balance
Definition at line 1654 of file videocapture.cpp.
 {
     int res = 0;
     res += ll_isp_aecagc_enable(0, active);
     res += ll_isp_aecagc_enable(1, active);
     return res;
 }
Referenced by VideoCapture::resetAECAGC(), VideoCapture::setExposure(), and VideoCapture::setGain().
getAECAGC()
bool getAECAGC ()
Get the status of the automatic Exposure and Gain control.
Returns
the status of the automatic Exposure and Gain control
Definition at line 1662 of file videocapture.cpp.
 {
     int resL = ll_isp_is_aecagc(0);
     int resR = ll_isp_is_aecagc(1);
     return (resL && resR);
 }
Referenced by VideoCapture::setExposure(), and VideoCapture::setGain().
resetAECAGC()
void resetAECAGC ()
Reset the automatic Exposure and Gain control value to default value.
Definition at line 1669 of file videocapture.cpp.
 {
     setAECAGC(true);
 }
References VideoCapture::setAECAGC().
Referenced by VideoCapture::initializeVideo().
setGain()
void setGain (CAM_SENS_POS cam, int gain)
Set the Gain value (disable Exposure and Gain control if active)
Parameters
cam position of the camera sensor (see CAM_SENS_POS)
gain Gain value in the range [0,100]
Definition at line 1674 of file videocapture.cpp.
 {
     if(getAECAGC())
         setAECAGC(false);
     if (gain <= DEFAULT_MIN_GAIN)
         gain = DEFAULT_MIN_GAIN;
     else if (gain >= DEFAULT_MAX_GAIN)
         gain = DEFAULT_MAX_GAIN;
     uint8_t ucGainH=0, ucGainM=0, ucGainL=0;
     int rawGain = calcRawGainValue(gain);
     int sensorId = static_cast<int>(cam);
     ucGainM = (rawGain >> 8) & 0xff;
     ucGainL = rawGain & 0xff;
     ll_isp_set_gain(ucGainH, ucGainM, ucGainL, sensorId);
 }
References VideoCapture::getAECAGC(), and VideoCapture::setAECAGC().
getGain()
int getGain (CAM_SENS_POS cam)
Get the current Gain value.
Parameters
cam position of the camera sensor (see CAM_SENS_POS)
Returns
the current Gain value
Definition at line 1696 of file videocapture.cpp.
 {
     int rawGain=0;
     uint8_t val[3];
     memset(val, 0, 3);
     int sensorId = static_cast<int>(cam);
     int r = ll_isp_get_gain(val, sensorId);
     if(r<0)
         return r;
     rawGain = (int) ((val[1] << 8) + val[0]);
     return calcGainValue(rawGain);
 }
setExposure()
void setExposure (CAM_SENS_POS cam, int exposure)
Set the Exposure value (disable Exposure and Gain control if active)
Parameters
cam position of the camera sensor (see CAM_SENS_POS)
exposure Exposure value in the range [0,100]
Definition at line 1712 of file videocapture.cpp.
 {
     unsigned char ucExpH, ucExpM, ucExpL;
     if(getAECAGC())
         setAECAGC(false);
     if(exposure < DEFAULT_MIN_EXP)
         exposure = DEFAULT_MIN_EXP;
     if(exposure > DEFAULT_MAX_EXP)
         exposure = DEFAULT_MAX_EXP;
     int rawExp = (mExpoureRawMax * ((float) exposure / 100.0));
     if(rawExp<EXP_RAW_MIN)
         rawExp = EXP_RAW_MIN;
     std::cout << "Set Raw Exp: " << rawExp << std::endl;
     int sensorId = static_cast<int>(cam);
     ucExpH = (rawExp >> 12) & 0xff;
     ucExpM = (rawExp >> 4) & 0xff;
     ucExpL = (rawExp << 4) & 0xf0;
     ll_isp_set_exposure(ucExpH, ucExpM, ucExpL, sensorId);
 }
References VideoCapture::getAECAGC(), and VideoCapture::setAECAGC().
getExposure()
int getExposure (CAM_SENS_POS cam)
Get the current Exposure value.
Parameters
cam position of the camera sensor (see CAM_SENS_POS)
Returns
the current Exposure value
Definition at line 1738 of file videocapture.cpp.
 {
     int rawExp=0;
     unsigned char val[3];
     memset(val, 0, 3);
     int sensorId = static_cast<int>(cam);
     int r = ll_isp_get_exposure(val, sensorId);
     if(r<0)
         return r;
     rawExp = (int) ((val[2] << 12) + (val[1] << 4) + (val[0] >> 4));
     std::cout << "Get Raw Exp: " << rawExp << std::endl;
     int exposure = static_cast<int>(std::round((100.0*rawExp)/mExpoureRawMax));
     return exposure;
 }
getSerialNumber()
int getSerialNumber ()
Retrieve the serial number of the connected camera.
Returns
the serial number of the connected camera
Examples
zed_oc_video_example.cpp.
Definition at line 539 of file videocapture.cpp.
 {
     if(!mInitialized)
         return -1;
     int ulValue = -1;
     uint8_t UNIQUE_BUF[384];
     memset(UNIQUE_BUF, 0, 384);
     int res = -1;
     int try_count = 0;
     while(res!=0)
     {
         res = ll_SPI_FlashProgramRead(&UNIQUE_BUF[0], UNIQUE_ID_START, 64);
         //check bytes read
         if (UNIQUE_BUF[0] != 'O') {
             res =  -1;
         }
         if (UNIQUE_BUF[1] != 'V') {
             res =  -1;
         }
         try_count++;
         if (try_count>500)
             break;
         usleep(1000);
     }
     if (res != 0)
         return -1;
     //check bytes read
     if (UNIQUE_BUF[0] != 'O') {
         return -1;
     }
     if (UNIQUE_BUF[1] != 'V') {
         return -1;
     }
     ulValue = (UNIQUE_BUF[2] << 24) + (UNIQUE_BUF[3] << 16) + (UNIQUE_BUF[4] << 8) + UNIQUE_BUF[5];
     char buff[128];
     memset(buff, 0, 128);
     sprintf(buff, "%x", ulValue);
     return (int) atoi(buff);
 }
enableSensorSync()
bool enableSensorSync (SensorCapture * sensCap = nullptr)
Enable synchronizations between Camera frame and Sensors timestamps.
Parameters
sensCap pointer to SensorCapture object
Returns
true if synchronization has been correctly started
Definition at line 1810 of file videocapture.cpp.
 {
     if(!sensCap)
         return false;
     // Activate low level sync mechanism
     ll_activate_sync();
     mSyncEnabled = true;
     mSensPtr = sensCap;
     mSensPtr->setVideoPtr(this);
     return true;
 }
References SensorCapture::setVideoPtr().
setReadyToSync()
void setReadyToSync () inline
Indicates that the SensorCapture object received the HW sync signal and a frame must be synchronized to the last Sensor Data.
Definition at line 313 of file videocapture.hpp.
 { mSensReadyToSync=true; }