ZED Open Capture: sl_oc::sensors::SensorCapture Class Reference
sl_oc::sensors::SensorCapture Class Reference
The SensorCapture class provides sensor grabbing functions for the Stereolabs ZED Mini and ZED2 camera models.
#include <sensorcapture.hpp>
Public Member Functions
SensorCapture (sl_oc::VERBOSITY verbose_lvl=sl_oc::VERBOSITY::ERROR)
The default constructor.
virtual ~SensorCapture ()
The class destructor.
std::vector< int > getDeviceList (bool refresh=false)
Get the list of the serial number of all the available devices.
bool initializeSensors (int sn=-1)
Open a connection to the MCU of a ZED Mini or a ZED2 camera using the specified serial number or searching for the first available device.
void getFirmwareVersion (uint16_t &fw_major, uint16_t &fw_minor)
Get the MCU firmware version in form [fw_major].[fw_minor].
int getSerialNumber ()
Retrieve the serial number of the connected camera.
const data::Imu & getLastIMUData (uint64_t timeout_usec=1500)
Get the last received IMU data.
const data::Magnetometer & getLastMagnetometerData (uint64_t timeout_usec=100)
Get the last received Magnetometer data.
const data::Environment & getLastEnvironmentData (uint64_t timeout_usec=100)
Get the last received Environment data.
const data::Temperature & getLastCameraTemperatureData (uint64_t timeout_usec=100)
Get the last received camera sensors temperature data.
void updateTimestampOffset (uint64_t frame_ts)
Called by VideoCapture to update timestamp offset.
void setStartTimestamp (uint64_t start_ts)
Called by VideoCapture to sync timestamps reference point.
void setVideoPtr (video::VideoCapture *videoPtr)
Called by VideoCapture to set the pointer to it.
Static Public Member Functions
static bool resetSensorModule (int serial_number=0)
Perform a SW reset of the Sensors Module. To be called in case one of the sensors stops to work correctly.
static bool resetVideoModule (int serial_number=0)
Perform a reset of the video module without resetting the sensor module. To be called in case the Video module stops to work correctly.
Detailed Description
The SensorCapture class provides sensor grabbing functions for the Stereolabs ZED Mini and ZED2 camera models.
Examples
zed_oc_sensors_example.cpp, and zed_oc_sync_example.cpp.
Definition at line 132 of file sensorcapture.hpp.
Constructor & Destructor Documentation
SensorCapture()
sl_oc::sensors::SensorCapture::SensorCapture (sl_oc::VERBOSITY verbose_lvl = sl_oc::VERBOSITY::ERROR)
The default constructor.
Parameters
verbose_lvl enable useful information to debug the class behaviours while running
Definition at line 36 of file sensorcapture.cpp.
 {
     mVerbose = verbose_lvl;
     if( mVerbose )
     {
         std::string ver =
                 "ZED Open Capture - Sensors module - Version: "
                 + std::to_string(mMajorVer) + "."
                 + std::to_string(mMinorVer) + "."
                 + std::to_string(mPatchVer);
         INFO_OUT(mVerbose,ver );
     }
 }
~SensorCapture()
sl_oc::sensors::SensorCapture::~SensorCapture () virtual
The class destructor.
Definition at line 51 of file sensorcapture.cpp.
 {
     close();
 }
Member Function Documentation
getDeviceList()
std::vector< int > sl_oc::sensors::SensorCapture::getDeviceList (bool refresh = false)
Get the list of the serial number of all the available devices.
Parameters
refresh if true USB device tree is parsed to search for modifications (new device connected/disconnected)
Returns
a vector containing the serial number of all the available devices
Examples
zed_oc_sensors_example.cpp.
Definition at line 107 of file sensorcapture.cpp.
 {
     if(mSlDevPid.size()==0 || refresh)
         enumerateDevices();
     std::vector<int> sn_vec;
     for(std::map<int,uint16_t>::iterator it = mSlDevPid.begin(); it != mSlDevPid.end(); ++it) {
         sn_vec.push_back(it->first);
     }
     return sn_vec;
 }
Referenced by main().
getFirmwareVersion()
void sl_oc::sensors::SensorCapture::getFirmwareVersion (uint16_t & fw_major, uint16_t & fw_minor)
Get the MCU firmware version in form [fw_major].[fw_minor].
Parameters
fw_major the major firmware version number
fw_minor the minor firmware version number
Examples
zed_oc_sensors_example.cpp.
Definition at line 191 of file sensorcapture.cpp.
 {
     if(mDevSerial==-1)
         return;
     uint16_t release = mSlDevFwVer[mDevSerial];
     fw_major = release>>8;
     fw_minor = release&0x00FF;
 }
Referenced by main().
getLastCameraTemperatureData()
const data::Temperature & sl_oc::sensors::SensorCapture::getLastCameraTemperatureData (uint64_t timeout_usec = 100)
Get the last received camera sensors temperature data.
Parameters
timeout_usec data grabbing timeout in milliseconds.
Returns
returns a reference to the last received data.
Examples
zed_oc_sensors_example.cpp.
Definition at line 853 of file sensorcapture.cpp.
 {
     // ----> Wait for a new frame
     uint64_t time_count = (timeout_usec<100?100:timeout_usec)/10;
     while( !mNewCamTempData )
     {
         if(time_count==0)
         {
             if(mLastCamTempData.valid!=data::Temperature::NOT_PRESENT)
                 mLastCamTempData.valid = data::Temperature::OLD_VAL;
             return mLastCamTempData;
         }
         time_count--;
         usleep(10);
     }
     // <---- Wait for a new frame
     // Get the frame mutex
     const std::lock_guard<std::mutex> lock(mCamTempMutex);
     mNewCamTempData = false;
     return mLastCamTempData;
 }
References sl_oc::sensors::data::Temperature::NOT_PRESENT, sl_oc::sensors::data::Temperature::OLD_VAL, and sl_oc::sensors::data::Temperature::valid.
Referenced by main().
getLastEnvironmentData()
const data::Environment & sl_oc::sensors::SensorCapture::getLastEnvironmentData (uint64_t timeout_usec = 100)
Get the last received Environment data.
Parameters
timeout_usec data grabbing timeout in milliseconds.
Returns
returns a reference to the last received data.
Examples
zed_oc_sensors_example.cpp.
Definition at line 830 of file sensorcapture.cpp.
 {
     // ----> Wait for a new frame
     uint64_t time_count = (timeout_usec<100?100:timeout_usec)/10;
     while( !mNewEnvData )
     {
         if(time_count==0)
         {
             if(mLastEnvData.valid!=data::Environment::NOT_PRESENT)
                 mLastEnvData.valid = data::Environment::OLD_VAL;
             return mLastEnvData;
         }
         time_count--;
         usleep(10);
     }
     // <---- Wait for a new frame
     // Get the frame mutex
     const std::lock_guard<std::mutex> lock(mEnvMutex);
     mNewEnvData = false;
     return mLastEnvData;
 }
References sl_oc::sensors::data::Environment::NOT_PRESENT, sl_oc::sensors::data::Environment::OLD_VAL, and sl_oc::sensors::data::Environment::valid.
Referenced by main().
getLastIMUData()
const data::Imu & sl_oc::sensors::SensorCapture::getLastIMUData (uint64_t timeout_usec = 1500)
Get the last received IMU data.
Parameters
timeout_usec data grabbing timeout in milliseconds.
Returns
returns a reference to the last received data.
Examples
zed_oc_sensors_example.cpp, and zed_oc_sync_example.cpp.
Definition at line 784 of file sensorcapture.cpp.
 {
     // ----> Wait for a new frame
     uint64_t time_count = (timeout_usec<100?100:timeout_usec)/100;
     while( !mNewIMUData )
     {
         if(time_count==0)
         {
             if(mLastIMUData.valid!=data::Imu::NOT_PRESENT)
                 mLastIMUData.valid = data::Imu::OLD_VAL;
             return mLastIMUData;
         }
         time_count--;
         usleep(100);
     }
     // <---- Wait for a new frame
     // Get the frame mutex
     const std::lock_guard<std::mutex> lock(mIMUMutex);
     mNewIMUData = false;
     return mLastIMUData;
 }
References sl_oc::sensors::data::Imu::NOT_PRESENT, sl_oc::sensors::data::Imu::OLD_VAL, and sl_oc::sensors::data::Imu::valid.
Referenced by getSensorThreadFunc(), and main().
getLastMagnetometerData()
const data::Magnetometer & sl_oc::sensors::SensorCapture::getLastMagnetometerData (uint64_t timeout_usec = 100)
Get the last received Magnetometer data.
Parameters
timeout_usec data grabbing timeout in milliseconds.
Returns
returns a reference to the last received data.
Examples
zed_oc_sensors_example.cpp.
Definition at line 807 of file sensorcapture.cpp.
 {
     // ----> Wait for a new frame
     uint64_t time_count = (timeout_usec<100?100:timeout_usec)/10;
     while( !mNewMagData )
     {
         if(time_count==0)
         {
             if(mLastMagData.valid!=data::Magnetometer::NOT_PRESENT)
                 mLastMagData.valid=data::Magnetometer::OLD_VAL;
             return mLastMagData;
         }
         time_count--;
         usleep(10);
     }
     // <---- Wait for a new frame
     // Get the frame mutex
     const std::lock_guard<std::mutex> lock(mMagMutex);
     mNewMagData = false;
     return mLastMagData;
 }
References sl_oc::sensors::data::Magnetometer::NOT_PRESENT, sl_oc::sensors::data::Magnetometer::OLD_VAL, and sl_oc::sensors::data::Magnetometer::valid.
Referenced by main().
getSerialNumber()
int sl_oc::sensors::SensorCapture::getSerialNumber ()
Retrieve the serial number of the connected camera.
Returns
the serial number of the connected camera
Examples
zed_oc_sensors_example.cpp.
Definition at line 202 of file sensorcapture.cpp.
 {
     if(mDevSerial==-1)
         return -1;
     return mDevSerial;
 }
Referenced by main().
initializeSensors()
bool sl_oc::sensors::SensorCapture::initializeSensors (int sn = -1)
Open a connection to the MCU of a ZED Mini or a ZED2 camera using the specified serial number or searching for the first available device.
Parameters
sn Serial Number of the camera. Use -1 to open connect to the first available device
Returns
returns true if the connection is correctly estabilished
Examples
zed_oc_sensors_example.cpp.
Definition at line 135 of file sensorcapture.cpp.
 {
     if(mSlDevPid.size()==0)
     {
         enumerateDevices();
     }
     std::string sn_str;
     if(sn==-1)
     {
         if(mSlDevPid.size()==0)
         {
             enumerateDevices();
         }
         if(mSlDevPid.size()==0)
         {
             ERROR_OUT(mVerbose,"No available ZED Mini or ZED2 cameras");
             return false;
         }
         sn = mSlDevPid.begin()->first;
     }
     uint16_t pid = mSlDevPid[sn];
     if(!open( pid,sn))
     {
         std::string msg = "Connection to device with sn ";
         msg += std::to_string(sn);
         msg += " failed";
         ERROR_OUT(mVerbose,msg);
         mDevFwVer = -1;
         mDevSerial = -1;
         return false;
     }
     if(mVerbose)
     {
         std::string msg = "Connected to device with sn ";
         msg += std::to_string(sn);
         INFO_OUT(mVerbose,msg);
     }
     mDevFwVer = mSlDevFwVer[sn];
     mDevPid = pid;
     mInitialized = startCapture();
     return true;
 }
Referenced by main().
resetSensorModule()
bool sl_oc::sensors::SensorCapture::resetSensorModule (int serial_number = 0) static
Perform a SW reset of the Sensors Module. To be called in case one of the sensors stops to work correctly.
Parameters
serial_number The serial number of the device to be reset (0 to reset the first available)
Returns
true if successful
Note
After the reset a new SensorCapture connection is required
The Sensors Module reset automatically performs a reset of the Video Module, so a new VideoCapture connection is required
Definition at line 673 of file sensorcapture.cpp.
 {
     int found_sn = serial_number;
     unsigned short pid;
     bool res = searchForConnectedDev(&found_sn, &pid);
     if(!res)
     {
         std::string msg;
         if(serial_number!=0)
         {
             msg = "[sl_oc::sensors::SensorCapture] WARNING: Sensors Module reset failed. Unable to find the Sensor Module with serial number ";
             msg += std::to_string(serial_number);
         }
         else
         {
             msg = "[sl_oc::sensors::SensorCapture] WARNING: Sensors Module reset failed. Unable to find the Sensor Module of a ZED2 camera. Please verify the USB connection.";
         }
         std::cerr << msg << std::endl;
         return false;
     }
     std::string sn_str = std::to_string(found_sn);
     std::wstring wide_sn_string = std::wstring(sn_str.begin(), sn_str.end());
     const wchar_t* wsn = wide_sn_string.c_str();
     hid_device* devHandle = hid_open(SL_USB_VENDOR, pid, wsn );
     if(!devHandle)
     {
         std::string msg = "Unable to open the MCU HID device";
         std::cerr << msg << std::endl;
         return false;
     }
     unsigned char  buf[65];
     buf[0] = static_cast<unsigned char>(usb::REP_ID_REQUEST_SET);
     buf[1] = static_cast<unsigned char>(usb::RQ_CMD_RST);
     hid_send_feature_report(devHandle, buf, 2);
     // Note: cannot verify the return value of the `hid_send_feature_report` command because the MCU is suddenly reset
     // and it cannot return a valid value
     sleep(2); // Wait for MCU and OV580 to reboot
     std::cerr << "[sl_oc::sensors::SensorCapture] INFO: Sensors Module reset successful" << std::endl;
     return true;
 }
resetVideoModule()
bool sl_oc::sensors::SensorCapture::resetVideoModule (int serial_number = 0) static
Perform a reset of the video module without resetting the sensor module. To be called in case the Video module stops to work correctly.
Parameters
Definition at line 725 of file sensorcapture.cpp.
 {
     int found_sn = serial_number;
     unsigned short pid;
     bool res = searchForConnectedDev(&found_sn, &pid);
     if(!res)
     {
         std::string msg;
         if(serial_number!=0)
         {
             msg = "[sl_oc::sensors::SensorCapture] WARNING: Video Module reset failed. Unable to find the Sensor Module with serial number ";
             msg += std::to_string(serial_number);
         }
         else
         {
             msg = "[sl_oc::sensors::SensorCapture] WARNING: Video Module reset failed. Unable to find the Sensor Module of a ZED2 camera. Please verify the USB connection.";
         }
         std::cerr << msg << std::endl;
         return false;
     }
     std::string sn_str = std::to_string(found_sn);
     std::wstring wide_sn_string = std::wstring(sn_str.begin(), sn_str.end());
     const wchar_t* wsn = wide_sn_string.c_str();
     hid_device* devHandle = hid_open(SL_USB_VENDOR, pid, wsn );
     if(!devHandle)
     {
         std::string msg = "Unable to open the MCU HID device";
         std::cerr << msg << std::endl;
         return false;
     }
     usb::OV580CmdStruct cmd;
     cmd.struct_id = usb::REP_ID_OV580_CMD;
     cmd.cmd = usb::OV580_CMD_RESET;
     cmd.info=0;
     unsigned char buf[65];
     memcpy(buf, &(cmd.struct_id), sizeof(usb::OV580CmdStruct));
     int ret = hid_send_feature_report(devHandle, buf, sizeof(usb::OV580CmdStruct));
     hid_close(devHandle);
     if(ret!=sizeof(usb::OV580CmdStruct)) {
         std::cerr << "[sl_oc::sensors::SensorCapture] INFO: Video Module reset failed" << std::endl;
         return false;
     }
     sleep(2); // Wait for OV580 to reboot
     std::cerr << "[sl_oc::sensors::SensorCapture] INFO: Video Module reset successful" << std::endl;
     return true;
 }
setStartTimestamp()
void sl_oc::sensors::SensorCapture::setStartTimestamp (uint64_t start_ts) inline
Called by VideoCapture to sync timestamps reference point.
Definition at line 229 of file sensorcapture.hpp.
setVideoPtr()
void sl_oc::sensors::SensorCapture::setVideoPtr (video::VideoCapture * videoPtr) inline
Called by VideoCapture to set the pointer to it.
Definition at line 230 of file sensorcapture.hpp.
Referenced by sl_oc::video::VideoCapture::enableSensorSync().
updateTimestampOffset()
void sl_oc::sensors::SensorCapture::updateTimestampOffset (uint64_t frame_ts)
Called by VideoCapture to update timestamp offset.
Definition at line 563 of file sensorcapture.cpp.
 {
     static int64_t offset_sum = 0;
     static int count = 0;
     offset_sum += (static_cast<int64_t>(mSyncTs) - static_cast<int64_t>(frame_ts));
     count++;
     if(count==3)
     {
         int64_t offset = offset_sum/count;
         mSyncOffset += offset;
 #if 0
         std::cout << "Offset: " << offset << std::endl;
         std::cout << "mSyncOffset: " << mSyncOffset << std::endl;
 #endif
         offset_sum = 0;
         count=0;
     }
 }
The documentation for this class was generated from the following files:
sensorcapture.hpp
sensorcapture.cpp