ZED Open Capture: sl_oc::video::VideoCapture Class Reference
sl_oc::video::VideoCapture Class Reference
The VideoCapture class provides image grabbing functions and settings control for all the Stereolabs camera models.
#include <videocapture.hpp>
Public Member Functions
VideoCapture (VideoParams params=VideoParams())
The default constructor.
virtual ~VideoCapture ()
The class destructor.
bool initializeVideo (int devId=-1)
Open a ZED camera using the specified ID or searching for the first available.
const Frame & getLastFrame (uint64_t timeout_msec=100)
Get the last received camera image.
void getFrameSize (int &width, int &height)
Get the size of the camera frame.
int setLEDstatus (bool status)
Set the status of the camera led.
int getLEDstatus (bool *status)
Get the status of the camera led.
int toggleLED (bool *value)
Toggle the status of the camera led.
void setBrightness (int brightness)
Set the Brightness value.
int getBrightness ()
Get the Brightness value.
void resetBrightness ()
Reset the Brightness value to default value.
void setSharpness (int sharpness)
Set the Sharpness value.
int getSharpness ()
Get the Sharpness value.
void resetSharpness ()
Reset the Sharpness value to default value.
void setContrast (int contrast)
Set the Contrast value.
int getContrast ()
Get the Contrast value.
void resetContrast ()
Reset the Contrast value to default value.
void setHue (int hue)
Set the Hue value.
int getHue ()
Get the Hue value.
void resetHue ()
Reset the Hue value to default value.
void setSaturation (int saturation)
Set the Saturation value.
int getSaturation ()
Get the Saturation value.
void resetSaturation ()
Reset the Saturation value to default value.
void setWhiteBalance (int wb)
Set the White Balance value (disable auto White Balance if active)
int getWhiteBalance ()
Get the White Balance value.
void setAutoWhiteBalance (bool active)
Enable/Disable the automatic White Balance control.
bool getAutoWhiteBalance ()
Get the status of the automatic White Balance control.
void resetAutoWhiteBalance ()
Reset the automatic White Balance control value to default value.
void setGamma (int gamma)
Set the Gamma value.
int getGamma ()
Get the Gamma value.
void resetGamma ()
Reset the Gamma value to default value.
int setAECAGC (bool active)
Enable/Disable the automatic Exposure and Gain control.
bool getAECAGC ()
Get the status of the automatic Exposure and Gain control.
void resetAECAGC ()
Reset the automatic Exposure and Gain control value to default value.
bool setROIforAECAGC (CAM_SENS_POS side, uint16_t x, uint16_t y, uint16_t w, uint16_t h)
Set Region Of Interest (ROI) for AECAGC control.
bool resetROIforAECAGC (CAM_SENS_POS side)
Reset the ROI for AECAGC control.
bool getROIforAECAGC (CAM_SENS_POS side, uint16_t &x, uint16_t &y, uint16_t &w, uint16_t &h)
Get the coordinates of the current ROI for AECAGC control.
void setGain (CAM_SENS_POS cam, int gain)
Set the Gain value (disable Exposure and Gain control if active)
int getGain (CAM_SENS_POS cam)
Get the current Gain value.
void setExposure (CAM_SENS_POS cam, int exposure)
Set the Exposure value (disable Exposure and Gain control if active)
int getExposure (CAM_SENS_POS cam)
Get the current Exposure value.
int getSerialNumber ()
Retrieve the serial number of the connected camera.
void setColorBars (int side, bool c)
Utils fct to set Color Bars on Image.
std::string getDeviceName ()
Retrieve the OS device name.
int getDeviceId ()
Retrieve the OS device index.
bool enableAecAgcSensLogging (bool enable, int frame_skip=10)
Start logging to file of AEG/AGC camera registers.
void saveAllISPRegisters (std::string filename)
Save all ISP camera registers into a file.
void saveAllSensorsRegisters (std::string filename)
Save all sensors ctrl register.
bool enableSensorSync (sensors::SensorCapture *sensCap=nullptr)
Enable synchronizations between Camera frame and Sensors timestamps.
void setReadyToSync ()
Indicates that the SensorCapture object received the HW sync signal and a frame must be synchronized to the last Sensor Data.
bool resetAGCAECregisters ()
Detailed Description
The VideoCapture class provides image grabbing functions and settings control for all the Stereolabs camera models.
Examples
zed_oc_control_example.cpp, zed_oc_depth_example.cpp, zed_oc_rectify_example.cpp, zed_oc_sync_example.cpp, zed_oc_tune_stereo_sgbm.cpp, and zed_oc_video_example.cpp.
Definition at line 64 of file videocapture.hpp.
Constructor & Destructor Documentation
VideoCapture()
sl_oc::video::VideoCapture::VideoCapture (VideoParams params = VideoParams())
The default constructor.
Parameters
params the initialization parameters (see VideoParams)
Definition at line 115 of file videocapture.cpp.
 {
     memcpy( &mParams, &params, sizeof(VideoParams) );
     if( mParams.verbose )
     {
         std::string ver =
                 "ZED Open Capture - Camera module - Version: "
                 + std::to_string(mMajorVer) + "."
                 + std::to_string(mMinorVer) + "."
                 + std::to_string(mPatchVer);
         INFO_OUT(mParams.verbose,ver);
     }
     // Check that FPS is coherent with user resolution
     checkResFps( );
     // Calculate gain zones (required because the raw gain control is not continuous in the range of values)
     mGainSegMax = (GAIN_ZONE4_MAX-GAIN_ZONE4_MIN)+(GAIN_ZONE3_MAX-GAIN_ZONE3_MIN)+(GAIN_ZONE2_MAX-GAIN_ZONE2_MIN)+(GAIN_ZONE1_MAX-GAIN_ZONE1_MIN);
     // FPS mapping
     if( mFps <= 15 )
         mExpoureRawMax = EXP_RAW_MAX_15FPS;
     else if( mFps <= 30 )
         mExpoureRawMax = EXP_RAW_MAX_30FPS;
     else if( mFps <= 60 )
         mExpoureRawMax = EXP_RAW_MAX_60FPS;
     else
         mExpoureRawMax = EXP_RAW_MAX_100FPS;
 }
References params, and sl_oc::video::VideoParams::verbose.
~VideoCapture()
sl_oc::video::VideoCapture::~VideoCapture () virtual
The class destructor.
Definition at line 146 of file videocapture.cpp.
 {
     reset();
 }
Member Function Documentation
enableAecAgcSensLogging()
bool sl_oc::video::VideoCapture::enableAecAgcSensLogging (bool enable, int frame_skip = 10)
Start logging to file of AEG/AGC camera registers.
Parameters
enable set to true to enable logging
frame_skip number of frames to skip when logging to file
Returns
true if log file can be correctly created/closed
Examples
zed_oc_control_example.cpp.
Definition at line 1939 of file videocapture.cpp.
 {
     if(!enable)
     {
         mLogEnable=false;
         if(mLogFileLeft.is_open())
         {
             mLogFileLeft.close();
         }
         if(mLogFileRight.is_open())
         {
             mLogFileRight.close();
         }
         return true;
     }
     mLogFrameSkip = frame_skip;
     mLogFilenameLeft = getCurrentDateTime(DATE);
     mLogFilenameLeft += "_";
     mLogFilenameLeft += getCurrentDateTime(TIME);
     mLogFilenameLeft += "_agc_aec_registers-LEFT.csv";
     mLogFilenameRight = getCurrentDateTime(DATE);
     mLogFilenameRight += "_";
     mLogFilenameRight += getCurrentDateTime(TIME);
     mLogFilenameRight += "_agc_aec_registers-RIGHT.csv";
     mLogFileLeft.open(mLogFilenameLeft, std::ofstream::out );
     mLogFileRight.open(mLogFilenameRight, std::ofstream::out );
     if(mLogFileLeft.bad())
     {
         std::cerr << "Logging not started. Error creating the log file: '" << mLogFilenameLeft << "'" << std::endl;
         mLogEnable = false;
         return false;
     }
     if(mLogFileRight.bad())
     {
         std::cerr << "Logging not started. Error creating the log file: '" << mLogFilenameRight << "'" << std::endl;
         mLogEnable = false;
         mLogFileLeft.close();
         return false;
     }
     mLogFileLeft << "TIMESTAMP" << LOG_SEP;
     mLogFileLeft << "OV580-ISP_EN_HIGH" << LOG_SEP;
     mLogFileLeft << "OV580-yavg_low" << LOG_SEP;
     mLogFileLeft << "OV580-yavg_high" << LOG_SEP;
     mLogFileLeft << "OV580-interrupt_ctrl1";
     mLogFileRight << "TIMESTAMP" << LOG_SEP;
     mLogFileRight << "OV580-ISP_EN_HIGH" << LOG_SEP;
     mLogFileRight << "OV580-yavg_low" << LOG_SEP;
     mLogFileRight << "OV580-yavg_high" << LOG_SEP;
     mLogFileRight << "OV580-interrupt_ctrl1";
     for (int addr = 0x00; addr <= 0x22; ++addr)
     {
         mLogFileLeft << LOG_SEP << "OV580-YAVG[0x" << std::hex << std::setfill('0') << std::setw(2) << addr << "]";
         mLogFileRight << LOG_SEP << "OV580-YAVG[0x" << std::hex << std::setfill('0') << std::setw(2) << addr << "]";
     }
     for (int addr = 0x3500; addr <= 0x3515; ++addr)
     {
         mLogFileLeft << LOG_SEP << "OV4689-GAIN_EXP[0x" << std::hex << std::setfill('0') << std::setw(4) << addr << "]";
         mLogFileRight << LOG_SEP << "OV4689-GAIN_EXP[0x" << std::hex << std::setfill('0') << std::setw(4) << addr << "]";
     }
     mLogFileLeft << std::endl;
     mLogFileRight << std::endl;
     mLogEnable = true;
     return true;
 }
Referenced by main().
enableSensorSync()
bool sl_oc::video::VideoCapture::enableSensorSync (sensors::SensorCapture * sensCap = nullptr)
Enable synchronizations between Camera frame and Sensors timestamps.
Parameters
sensCap pointer to SensorCapture object
Returns
true if synchronization has been correctly started
Definition at line 2151 of file videocapture.cpp.
 {
     if(!sensCap)
         return false;
     // Activate low level sync mechanism
     ll_activate_sync();
     mSyncEnabled = true;
     mSensPtr = sensCap;
     mSensPtr->setVideoPtr(this);
     return true;
 }
References sl_oc::sensors::SensorCapture::setVideoPtr().
Referenced by main().
getAECAGC()
bool sl_oc::video::VideoCapture::getAECAGC ()
Get the status of the automatic Exposure and Gain control.
Returns
the status of the automatic Exposure and Gain control
Examples
zed_oc_control_example.cpp.
Definition at line 1711 of file videocapture.cpp.
 {
     int resL = ll_isp_is_aecagc(0);
     int resR = ll_isp_is_aecagc(1);
     return (resL && resR);
 }
Referenced by setExposure(), and setGain().
getAutoWhiteBalance()
bool sl_oc::video::VideoCapture::getAutoWhiteBalance ()
Get the status of the automatic White Balance control.
Returns
the status of the automatic White Balance control
Examples
zed_oc_control_example.cpp.
Definition at line 1664 of file videocapture.cpp.
 {
     return (getCameraControlSettings(LINUX_CTRL_AWB_AUTO)!=0);
 }
Referenced by setWhiteBalance().
getBrightness()
int sl_oc::video::VideoCapture::getBrightness ()
Get the Brightness value.
Returns
the current Brightness value
Examples
zed_oc_control_example.cpp.
Definition at line 1585 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_BRIGHTNESS);
 }
getContrast()
int sl_oc::video::VideoCapture::getContrast ()
Get the Contrast value.
Returns
the current Contrast value
Examples
zed_oc_control_example.cpp.
Definition at line 1615 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_CONTRAST);
 }
getDeviceId()
int sl_oc::video::VideoCapture::getDeviceId () inline
Retrieve the OS device index.
Returns
the OS device index
Definition at line 358 of file videocapture.hpp.
 {return mDevId;}
getDeviceName()
std::string sl_oc::video::VideoCapture::getDeviceName () inline
Retrieve the OS device name.
Returns
the OS device name
Examples
zed_oc_video_example.cpp.
Definition at line 352 of file videocapture.hpp.
 {return mDevName;}
Referenced by main().
getExposure()
int sl_oc::video::VideoCapture::getExposure (CAM_SENS_POS cam)
Get the current Exposure value.
Parameters
cam position of the camera sensor (see CAM_SENS_POS)
Returns
the current Exposure value
Examples
zed_oc_control_example.cpp.
Definition at line 1867 of file videocapture.cpp.
 {
     int rawExp=0;
     unsigned char val[3];
     memset(val, 0, 3);
     int sensorId = static_cast<int>(cam);
     int r = ll_isp_get_exposure(val, sensorId);
     if(r<0)
         return r;
     rawExp = (int) ((val[2] << 12) + (val[1] << 4) + (val[0] >> 4));
     //std::cout << "Get Raw Exp: " << rawExp << std::endl;
     int exposure = static_cast<int>(std::round((100.0*rawExp)/mExpoureRawMax));
     return exposure;
 }
getFrameSize()
void sl_oc::video::VideoCapture::getFrameSize (int & width, int & height) inline
Get the size of the camera frame.
Parameters
width the frame width
height the frame height
Examples
zed_oc_depth_example.cpp, and zed_oc_rectify_example.cpp.
Definition at line 105 of file videocapture.hpp.
 {width=mWidth;height=mHeight;}
Referenced by main().
getGain()
int sl_oc::video::VideoCapture::getGain (CAM_SENS_POS cam)
Get the current Gain value.
Parameters
cam position of the camera sensor (see CAM_SENS_POS)
Returns
the current Gain value
Examples
zed_oc_control_example.cpp.
Definition at line 1825 of file videocapture.cpp.
 {
     int rawGain=0;
     uint8_t val[3];
     memset(val, 0, 3);
     int sensorId = static_cast<int>(cam);
     int r = ll_isp_get_gain(val, sensorId);
     if(r<0)
         return r;
     rawGain = (int) ((val[1] << 8) + val[0]);
     return calcGainValue(rawGain);
 }
getGamma()
int sl_oc::video::VideoCapture::getGamma ()
Get the Gamma value.
Returns
the current Gamma value
Examples
zed_oc_control_example.cpp.
Definition at line 1699 of file videocapture.cpp.
{
     return getCameraControlSettings(LINUX_CTRL_GAMMA);
 }
getHue()
int sl_oc::video::VideoCapture::getHue ()
Get the Hue value.
Returns
the current Hue value
Examples
zed_oc_control_example.cpp.
Definition at line 1630 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_HUE);
 }
getLastFrame()
const Frame & sl_oc::video::VideoCapture::getLastFrame (uint64_t timeout_msec = 100)
Get the last received camera image.
Parameters
timeout_msec frame grabbing timeout in millisecond.
Returns
returns a reference to the last received frame as pointer.
Note
To check if a new frame is available it is possible to compare the timestamp of the returned frame with the timestamp of the previous valid frame
Frame received will contains the RAW buffer from the camera, in YUV4:2:2 color format and in side by side mode. Images must then be converted to RGB for proper display and will not be rectified.
Examples
zed_oc_depth_example.cpp, zed_oc_rectify_example.cpp, and zed_oc_video_example.cpp.
Definition at line 890 of file videocapture.cpp.
 {
     // ----> Wait for a new frame
     uint64_t time_count = timeout_msec*10;
     while( !mNewFrame )
     {
         if(time_count==0)
         {
             return mLastFrame;
         }
         time_count--;
         usleep(100);
     }
     // <---- Wait for a new frame
     // Get the frame mutex
     const std::lock_guard<std::mutex> lock(mBufMutex);
     mNewFrame = false;
     return mLastFrame;
 }
Referenced by main().
getLEDstatus()
int sl_oc::video::VideoCapture::getLEDstatus (bool * status)
Get the status of the camera led.
Parameters
status returned status: true for "ON", false for "OFF"
Returns
returns a negative value if an error occurred
Definition at line 1418 of file videocapture.cpp.
 {
     if( status==nullptr)
     {
         return -1;
     }
     uint8_t val;
     int hr = ll_set_gpio_direction(2, 1);
     hr += ll_get_gpio_value(2, &val);
     *status = val!=0;
     return hr;
 }
Referenced by toggleLED().
getROIforAECAGC()
bool sl_oc::video::VideoCapture::getROIforAECAGC (CAM_SENS_POS side, uint16_t & x, uint16_t & y, uint16_t & w, uint16_t & h)
Get the coordinates of the current ROI for AECAGC control.
Parameters
side position of the camera sensor (see CAM_SENS_POS)
x top left ROI rectangle X coordinate
y top left ROI rectangle Y coordinate
w ROI rectangle width
h ROI rectangle width
Returns
returns true if no errors occurred
Examples
zed_oc_control_example.cpp.
Definition at line 1773 of file videocapture.cpp.
 {
     uint8_t x_start_high = 0;
     uint8_t x_start_low = 0;
     uint8_t y_start_high =0;
     uint8_t y_start_low = 0;
     uint8_t w_start_high =0;
     uint8_t w_start_low = 0;
     uint8_t h_start_high = 0;
     uint8_t h_start_low = 0;
     uint32_t ulAddr = 0x801810C0;
     if (static_cast<int>(side)==1)
         ulAddr= 0x801818C0;
     int r =  ll_read_system_register(ulAddr,&x_start_high);ulAddr++;usleep(100);
     r +=  ll_read_system_register(ulAddr,&x_start_low);ulAddr++;usleep(100);
     r +=   ll_read_system_register(ulAddr,&y_start_high);ulAddr++;usleep(100);
     r +=   ll_read_system_register(ulAddr,&y_start_low);ulAddr++;usleep(100);
     r +=   ll_read_system_register(ulAddr,&w_start_high);ulAddr++;usleep(100);
     r +=   ll_read_system_register(ulAddr,&w_start_low);ulAddr++;usleep(100);
     r +=   ll_read_system_register(ulAddr,&h_start_high);ulAddr++;usleep(100);
     r +=   ll_read_system_register(ulAddr,&h_start_low);ulAddr++;usleep(100);
     x = x_start_high*256 + x_start_low;
     y = y_start_high*256 + y_start_low;
     w = w_start_high*256 + w_start_low;
     h = h_start_high*256 + h_start_low;
     return (r==0);
 }
getSaturation()
int sl_oc::video::VideoCapture::getSaturation ()
Get the Saturation value.
Returns
the current Saturation value
Examples
zed_oc_control_example.cpp.
Definition at line 1645 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_SATURATION);
 }
getSerialNumber()
int sl_oc::video::VideoCapture::getSerialNumber ()
Retrieve the serial number of the connected camera.
Returns
the serial number of the connected camera
Examples
zed_oc_depth_example.cpp, zed_oc_rectify_example.cpp, and zed_oc_video_example.cpp.
Definition at line 548 of file videocapture.cpp.
 {
     /*if(!mInitialized)
         return -1;*/
     int ulValue = -1;
     uint8_t UNIQUE_BUF[384];
     memset(UNIQUE_BUF, 0, 384);
     int res = -1;
     int try_count = 0;
     while(res!=0)
     {
         res = ll_SPI_FlashProgramRead(&UNIQUE_BUF[0], UNIQUE_ID_START, 64, true);
         //check bytes read
         if (UNIQUE_BUF[0] != 'O') {
             res =  -1;
         }
         if (UNIQUE_BUF[1] != 'V') {
             res =  -1;
         }
         try_count++;
         if (try_count>500)
             break;
         usleep(1000);
     }
     if (res != 0)
         return -1;
     //check bytes read
     if (UNIQUE_BUF[0] != 'O') {
         return -1;
     }
     if (UNIQUE_BUF[1] != 'V') {
         return -1;
     }
     ulValue = (UNIQUE_BUF[2] << 24) + (UNIQUE_BUF[3] << 16) + (UNIQUE_BUF[4] << 8) + UNIQUE_BUF[5];
     char buff[128];
     memset(buff, 0, 128);
     sprintf(buff, "%x", ulValue);
     return (int) atoi(buff);
 }
Referenced by main().
getSharpness()
int sl_oc::video::VideoCapture::getSharpness ()
Get the Sharpness value.
Returns
the current Sharpness value
Examples
zed_oc_control_example.cpp.
Definition at line 1600 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_SHARPNESS);
 }
getWhiteBalance()
int sl_oc::video::VideoCapture::getWhiteBalance ()
Get the White Balance value.
Returns
the current White Balance value
Examples
zed_oc_control_example.cpp.
Definition at line 1650 of file videocapture.cpp.
 {
     return getCameraControlSettings(LINUX_CTRL_AWB);
 }
initializeVideo()
bool sl_oc::video::VideoCapture::initializeVideo (int devId = -1)
Open a ZED camera using the specified ID or searching for the first available.
Parameters
devId Id of the camera (see /dev/video*). Use -1 to open the first available camera
Returns
returns true if the camera is correctly opened
Examples
zed_oc_depth_example.cpp, zed_oc_rectify_example.cpp, and zed_oc_video_example.cpp.
Definition at line 276 of file videocapture.cpp.
 {
     reset();
     bool opened=false;
     if( devId==-1 )
     {
         // Try to open all the devices until the first success (max allowed by v4l: 64)
         for( uint8_t id=0; id<64; id++ )
         {
             opened = openCamera( id );
             if(opened) break;
         }
     }
     else
     {
         opened = openCamera( static_cast<uint8_t>(devId) );
     }
     if(!opened)
     {
         return false;
     }
     mInitialized = startCapture();
     if( mParams.verbose && mInitialized)
     {
         std::string msg = "Device '" + mDevName + "' opened";
         INFO_OUT(mParams.verbose,msg );
     }
     setLEDstatus( true );
     resetAECAGC();
     resetAutoWhiteBalance();
     resetBrightness();
     resetContrast();
     resetGamma();
     resetHue();
     resetSaturation();
     resetSharpness();
     return mInitialized;
 }
References resetAECAGC(), resetAutoWhiteBalance(), resetBrightness(), resetContrast(), resetGamma(), resetHue(), resetSaturation(), resetSharpness(), setLEDstatus(), and sl_oc::video::VideoParams::verbose.
Referenced by main().
resetAECAGC()
void sl_oc::video::VideoCapture::resetAECAGC ()
Reset the automatic Exposure and Gain control value to default value.
Examples
zed_oc_control_example.cpp.
Definition at line 1718 of file videocapture.cpp.
 {
     setAECAGC(true);
 }
References setAECAGC().
Referenced by initializeVideo().
resetAGCAECregisters()
bool sl_oc::video::VideoCapture::resetAGCAECregisters ()
Examples
zed_oc_control_example.cpp.
Definition at line 2138 of file videocapture.cpp.
{
     int res = 0;
     res += ll_write_sensor_register( 0, 1, 0x3503, 0x04);
     res += ll_write_sensor_register( 1, 1, 0x3503, 0x04);
     res += ll_write_sensor_register( 0, 1, 0x3505, 0x00);
     res += ll_write_sensor_register( 1, 1, 0x3505, 0x00);
     return res==0;
 }
resetAutoWhiteBalance()
void sl_oc::video::VideoCapture::resetAutoWhiteBalance ()
Reset the automatic White Balance control value to default value.
Examples
zed_oc_control_example.cpp.
Definition at line 1674 of file videocapture.cpp.
 {
     setAutoWhiteBalance(true);
 }
References setAutoWhiteBalance().
Referenced by initializeVideo().
resetBrightness()
void sl_oc::video::VideoCapture::resetBrightness ()
Reset the Brightness value to default value.
Examples
zed_oc_control_example.cpp.
Definition at line 1580 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_BRIGHTNESS);
 }
Referenced by initializeVideo().
resetContrast()
void sl_oc::video::VideoCapture::resetContrast ()
Reset the Contrast value to default value.
Examples
zed_oc_control_example.cpp.
Definition at line 1610 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_CONTRAST);
 }
Referenced by initializeVideo().
resetGamma()
void sl_oc::video::VideoCapture::resetGamma ()
Reset the Gamma value to default value.
Examples
zed_oc_control_example.cpp.
Definition at line 1691 of file videocapture.cpp.
 {
     int def_value = DEFAULT_GAMMA_NOECT;
     setGammaPreset(0,def_value);
     setGammaPreset(1,def_value);
     setCameraControlSettings(LINUX_CTRL_GAMMA, def_value);
 }
Referenced by initializeVideo().
resetHue()
void sl_oc::video::VideoCapture::resetHue ()
Reset the Hue value to default value.
Examples
zed_oc_control_example.cpp.
Definition at line 1625 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_HUE);
 }
Referenced by initializeVideo().
resetROIforAECAGC()
bool sl_oc::video::VideoCapture::resetROIforAECAGC (CAM_SENS_POS side)
Reset the ROI for AECAGC control.
Parameters
side position of the camera sensor (see CAM_SENS_POS)
Returns
returns true if the ROI has been correctly reset
Examples
zed_oc_control_example.cpp.
Definition at line 1768 of file videocapture.cpp.
 {
     return setROIforAECAGC(side, 0,0, mWidth/2, mHeight);
 }
References setROIforAECAGC().
resetSaturation()
void sl_oc::video::VideoCapture::resetSaturation ()
Reset the Saturation value to default value.
Examples
zed_oc_control_example.cpp.
Definition at line 1640 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_SATURATION);
 }
Referenced by initializeVideo().
resetSharpness()
void sl_oc::video::VideoCapture::resetSharpness ()
Reset the Sharpness value to default value.
Examples
zed_oc_control_example.cpp.
Definition at line 1595 of file videocapture.cpp.
 {
     resetCameraControlSettings(LINUX_CTRL_SHARPNESS);
 }
Referenced by initializeVideo().
saveAllISPRegisters()
void sl_oc::video::VideoCapture::saveAllISPRegisters (std::string filename)
Save all ISP camera registers into a file.
Parameters
filename csv filename
Note
CSV file will contain Adress , L value, R value
Definition at line 2030 of file videocapture.cpp.
 {
     std::ofstream logFile;
     logFile.open(filename,std::ofstream::out);
     int res = 0;
     unsigned long long ulAddrL =  0x80181000;
     unsigned long long   ulAddrR =  0x80181800;
     for (int p = 0;p<0x800;p++)
     {
         uint8_t valL,valR;
         res += ll_read_system_register( ulAddrL+p, &valL);
         res += ll_read_system_register( ulAddrR+p, &valR);
         logFile <<"0x" << std::hex << std::setfill('0') << std::setw(8) << static_cast<unsigned long long>(ulAddrL+p)<<" , "<<std::hex << std::setfill('0') << std::setw(2) << static_cast<unsigned long long>(valL)<<" , "<<std::hex << std::setfill('0') << std::setw(2) << static_cast<unsigned long long>(valR)<<std::endl;
         usleep(10);
     }
     logFile.close();
 }
Referenced by main().
saveAllSensorsRegisters()
void sl_oc::video::VideoCapture::saveAllSensorsRegisters (std::string filename)
Save all sensors ctrl register.
Parameters
filename csv filename
Note
CSV file will contain Adress , L value, R value
Definition at line 2051 of file videocapture.cpp.
 {
     std::ofstream logFile;
     logFile.open(filename,std::ofstream::out);
     int res = 0;
     for (int addr = 0x3000; addr <= 0x6000; ++addr)
     {
         uint8_t valL,valR;
         res += ll_read_sensor_register( 0, 1, addr, &valL);
         res += ll_read_sensor_register( 1, 1, addr, &valR);
         usleep(10);
         logFile <<"0x" << std::hex << std::setfill('0') << std::setw(8) << static_cast<int>(addr)<<" , "<<std::hex << std::setfill('0') << std::setw(2) << static_cast<unsigned long long>(valL)<<" , "<<std::hex << std::setfill('0') << std::setw(2) << static_cast<unsigned long long>(valR)<<std::endl;
     }
     logFile.close();
 }
Referenced by main().
setAECAGC()
int sl_oc::video::VideoCapture::setAECAGC (bool active)
Enable/Disable the automatic Exposure and Gain control.
Parameters
active true to activate automatic White Balance
Examples
zed_oc_control_example.cpp.
Definition at line 1703 of file videocapture.cpp.
 {
     int res = 0;
     res += ll_isp_aecagc_enable(0, active);
     res += ll_isp_aecagc_enable(1, active);
     return res;
 }
Referenced by main(), resetAECAGC(), setExposure(), and setGain().
setAutoWhiteBalance()
void sl_oc::video::VideoCapture::setAutoWhiteBalance (bool active)
Enable/Disable the automatic White Balance control.
Parameters
active true to activate automatic White Balance
Examples
zed_oc_control_example.cpp.
Definition at line 1669 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_AWB_AUTO, active?1:0);
 }
Referenced by main(), resetAutoWhiteBalance(), and setWhiteBalance().
setBrightness()
void sl_oc::video::VideoCapture::setBrightness (int brightness)
Set the Brightness value.
Parameters
brightness Brightness value in the range [0,8]
Examples
zed_oc_control_example.cpp.
Definition at line 1575 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_BRIGHTNESS, brightness);
 }
setColorBars()
void sl_oc::video::VideoCapture::setColorBars (int side, bool c)
Utils fct to set Color Bars on Image.
Definition at line 2016 of file videocapture.cpp.
 {
     unsigned long long ulAddr2 = 0x80181080;
     if (side==1)
          ulAddr2 = 0x80181880;
     unsigned char ulValue2 =c?128:0;
     ll_write_system_register(ulAddr2,ulValue2);
 }
Referenced by main().
setContrast()
void sl_oc::video::VideoCapture::setContrast (int contrast)
Set the Contrast value.
Parameters
contrast Contrast value in the range [0,8]
Examples
zed_oc_control_example.cpp.
Definition at line 1605 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_CONTRAST, contrast);
 }
setExposure()
void sl_oc::video::VideoCapture::setExposure (CAM_SENS_POS cam, int exposure)
Set the Exposure value (disable Exposure and Gain control if active)
Parameters
cam position of the camera sensor (see CAM_SENS_POS)
exposure Exposure value in the range [0,100]
Examples
zed_oc_control_example.cpp.
Definition at line 1841 of file videocapture.cpp.
 {
     unsigned char ucExpH, ucExpM, ucExpL;
     if(getAECAGC())
         setAECAGC(false);
     if(exposure < DEFAULT_MIN_EXP)
         exposure = DEFAULT_MIN_EXP;
     if(exposure > DEFAULT_MAX_EXP)
         exposure = DEFAULT_MAX_EXP;
     int rawExp = (mExpoureRawMax * ((float) exposure / 100.0));
     if(rawExp<EXP_RAW_MIN)
         rawExp = EXP_RAW_MIN;
     //std::cout << "Set Raw Exp: " << rawExp << std::endl;
     int sensorId = static_cast<int>(cam);
     ucExpH = (rawExp >> 12) & 0xff;
     ucExpM = (rawExp >> 4) & 0xff;
     ucExpL = (rawExp << 4) & 0xf0;
     ll_isp_set_exposure(ucExpH, ucExpM, ucExpL, sensorId);
 }
References getAECAGC(), and setAECAGC().
setGain()
void sl_oc::video::VideoCapture::setGain (CAM_SENS_POS cam, int gain)
Set the Gain value (disable Exposure and Gain control if active)
Parameters
cam position of the camera sensor (see CAM_SENS_POS)
gain Gain value in the range [0,100]
Examples
zed_oc_control_example.cpp.
Definition at line 1803 of file videocapture.cpp.
 {
     if(getAECAGC())
         setAECAGC(false);
     if (gain <= DEFAULT_MIN_GAIN)
         gain = DEFAULT_MIN_GAIN;
     else if (gain >= DEFAULT_MAX_GAIN)
         gain = DEFAULT_MAX_GAIN;
     uint8_t ucGainH=0, ucGainM=0, ucGainL=0;
     int rawGain = calcRawGainValue(gain);
     int sensorId = static_cast<int>(cam);
     ucGainM = (rawGain >> 8) & 0xff;
     ucGainL = rawGain & 0xff;
     ll_isp_set_gain(ucGainH, ucGainM, ucGainL, sensorId);
 }
References getAECAGC(), and setAECAGC().
setGamma()
void sl_oc::video::VideoCapture::setGamma (int gamma)
Set the Gamma value.
Parameters
gamma Gamma value in the range [1,9]
Examples
zed_oc_control_example.cpp.
Definition at line 1679 of file videocapture.cpp.
 {
     int current_gamma = getCameraControlSettings(LINUX_CTRL_GAMMA);
     if (gamma!=current_gamma)
     {
         setGammaPreset(0,gamma);
         setGammaPreset(1,gamma);
         setCameraControlSettings(LINUX_CTRL_GAMMA, gamma);
     }
 }
setHue()
void sl_oc::video::VideoCapture::setHue (int hue)
Set the Hue value.
Parameters
hue Hue value in the range [0,11]
Examples
zed_oc_control_example.cpp.
Definition at line 1620 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_HUE, hue);
 }
setLEDstatus()
int sl_oc::video::VideoCapture::setLEDstatus (bool status)
Set the status of the camera led.
Parameters
status true for "ON", false for "OFF"
Returns
returns a negative value if an error occurred
Definition at line 1403 of file videocapture.cpp.
 {
     int hr = 0;
     //LED GPIO : GPIO 2
     if (status) {
         hr += ll_set_gpio_direction(2, 0);
         hr += ll_set_gpio_value(2, 1);
     } else {
         hr += ll_set_gpio_direction(2, 0);
         hr += ll_set_gpio_value(2, 0);
     }
     return hr;
 }
Referenced by initializeVideo(), and toggleLED().
setReadyToSync()
void sl_oc::video::VideoCapture::setReadyToSync () inline
Indicates that the SensorCapture object received the HW sync signal and a frame must be synchronized to the last Sensor Data.
Definition at line 397 of file videocapture.hpp.
 { mSensReadyToSync=true; }
setROIforAECAGC()
bool sl_oc::video::VideoCapture::setROIforAECAGC (CAM_SENS_POS side, uint16_t x, uint16_t y, uint16_t w, uint16_t h)
Set Region Of Interest (ROI) for AECAGC control.
Parameters
side position of the camera sensor (see CAM_SENS_POS)
x top left ROI rectangle X coordinate
y top left ROI rectangle Y coordinate
w ROI rectangle width
h ROI rectangle width
Returns
returns true if the ROI has been correctly set
Definition at line 1723 of file videocapture.cpp.
 {
     if(side!=CAM_SENS_POS::LEFT && side!=CAM_SENS_POS::RIGHT)
     {
         return false;
     }
     if(w==0 || h==0)
     {
         return false;
     }
     if((x+w)>(mWidth/2) || (y+h)>mHeight)
     {
         return false;
     }
     if(w*h<=100)
     {
         return false;
     }
     int x_start_high = x / 256;
     int x_start_low = (x - x_start_high * 256);
     int y_start_high = y / 256;
     int y_start_low = (y - x_start_high * 256);
     int w_start_high = w / 256;
     int w_start_low = (w - x_start_high * 256);
     int h_start_high = h / 256;
     int h_start_low = (h - x_start_high * 256);
     uint32_t ulAddr = 0x801810C0;
     if (static_cast<int>(side)==1)
         ulAddr= 0x801818C0;
     int r = ll_write_system_register(ulAddr,static_cast<uint8_t>(x_start_high));ulAddr++;usleep(100);
     r += ll_write_system_register(ulAddr,static_cast<uint8_t>(x_start_low));ulAddr++;usleep(100);
     r += ll_write_system_register(ulAddr,static_cast<uint8_t>(y_start_high));ulAddr++;usleep(100);
     r += ll_write_system_register(ulAddr,static_cast<uint8_t>(y_start_low));ulAddr++;usleep(100);
     r += ll_write_system_register(ulAddr,static_cast<uint8_t>(w_start_high));ulAddr++;usleep(100);
     r += ll_write_system_register(ulAddr,static_cast<uint8_t>(w_start_low));ulAddr++;usleep(100);
     r += ll_write_system_register(ulAddr,static_cast<uint8_t>(h_start_high));ulAddr++;usleep(100);
     r += ll_write_system_register(ulAddr,static_cast<uint8_t>(h_start_low));ulAddr++;usleep(100);
     return (r==0);
 }
References sl_oc::video::LEFT, and sl_oc::video::RIGHT.
Referenced by resetROIforAECAGC().
setSaturation()
void sl_oc::video::VideoCapture::setSaturation (int saturation)
Set the Saturation value.
Parameters
saturation Saturation value in the range [0,8]
Examples
zed_oc_control_example.cpp.
Definition at line 1635 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_SATURATION, saturation);
 }
setSharpness()
void sl_oc::video::VideoCapture::setSharpness (int sharpness)
Set the Sharpness value.
Parameters
sharpness Sharpness value in the range [0,8]
Examples
zed_oc_control_example.cpp.
Definition at line 1590 of file videocapture.cpp.
 {
     setCameraControlSettings(LINUX_CTRL_SHARPNESS, sharpness);
 }
setWhiteBalance()
void sl_oc::video::VideoCapture::setWhiteBalance (int wb)
Set the White Balance value (disable auto White Balance if active)
Parameters
wb White Balance value in the range [2800,6500]
Examples
zed_oc_control_example.cpp.
Definition at line 1655 of file videocapture.cpp.
 {
     // Disable auto white balance if active
     if (getAutoWhiteBalance() != 0)
         setAutoWhiteBalance(false);
     setCameraControlSettings(LINUX_CTRL_AWB, wb);
 }
References getAutoWhiteBalance(), and setAutoWhiteBalance().
toggleLED()
int sl_oc::video::VideoCapture::toggleLED (bool * value)
Toggle the status of the camera led.
Parameters
value returned status: true for "ON", false for "OFF"
Returns
returns a negative value if an error occurred
Examples
zed_oc_control_example.cpp.
Definition at line 1432 of file videocapture.cpp.
 {
     bool curVal;
     int ret = getLEDstatus( &curVal );
     if(ret==0)
     {
         bool newVal = !curVal;
         ret = setLEDstatus( newVal );
         if( ret==0 && value!=nullptr )
         {
             *value = newVal;
         }
     }
     return ret;
 }
References getLEDstatus(), and setLEDstatus().
The documentation for this class was generated from the following files:
videocapture.hpp
videocapture.cpp