ZED Open Capture: zed_oc_sensors_example.cpp File Reference
zed_oc_sensors_example.cpp File Reference
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Examples
zed_oc_sensors_example.cpp.
Definition at line 30 of file zed_oc_sensors_example.cpp.
 {
     // Set the verbose level
     sl_oc::VERBOSITY verbose = sl_oc::VERBOSITY::INFO;
     // Create a SensorCapture object
     sl_oc::sensors::SensorCapture sens(verbose);
     // ----> Get a list of available camera with sensor
     std::vector<int> devs = sens.getDeviceList();
     if( devs.size()==0 )
     {
         std::cerr << "No available ZED Mini or ZED2 cameras" << std::endl;
         return EXIT_FAILURE;
     }
     // <---- Get a list of available camera with sensor
     // ----> Inizialize the sensors
     if( !sens.initializeSensors( devs[0] ) )
     {
         std::cerr << "Connection failed" << std::endl;
         return EXIT_FAILURE;
     }
     std::cout << "Sensor Capture connected to camera sn: " << sens.getSerialNumber() << std::endl;
     // <---- Inizialize the sensors
     // ----> Get FW version information
     uint16_t fw_maior;
     uint16_t fw_minor;
     sens.getFirmwareVersion( fw_maior, fw_minor );
     std::cout << " * Firmware version: " << std::to_string(fw_maior) << "." << std::to_string(fw_minor) << std::endl;
     // <---- Get FW version information
     // ----> Variables to calculate sensors frequencies
     uint64_t last_imu_ts = 0;
     uint64_t last_mag_ts = 0;
     uint64_t last_env_ts = 0;
     uint64_t last_cam_temp_ts = 0;
     // <---- Variables to calculate sensors frequencies
     // Lets grab 4000 sensors data (about 10 seconds
     int count = 0;
     while(++count<4000)
     {
         // ----> Get IMU data with a timeout of 5 millisecods
         const sl_oc::sensors::data::Imu imuData = sens.getLastIMUData(5000);
         if( imuData.valid == sl_oc::sensors::data::Imu::NEW_VAL  )
         {
             std::cout << "**** New IMU data ****" << std::endl;
             std::cout << " * Timestamp: " << imuData.timestamp << " nsec" << std::endl;
             if(last_imu_ts!=0)
             {
                 std::cout << " * Frequency: " << 1e9/static_cast<float>(imuData.timestamp-last_imu_ts) << " Hz" << std::endl;
             }
             last_imu_ts = imuData.timestamp;
             std::cout << " * Accelerations [m/s²]: " << imuData.aX << " " << imuData.aY << " " << imuData.aZ << std::endl;
             std::cout << " * Angular Velocities [°/s]: " << imuData.gX << " " << imuData.gY << " " << imuData.gZ << std::endl;
         }
         // <---- Get IMU data with a timeout of 5 millisecods
         // ----> Get Magnetometer data with a timeout of 100 microseconds to not slow down fastest data (IMU)
         const sl_oc::sensors::data::Magnetometer magData = sens.getLastMagnetometerData(100);
         if( magData.valid == sl_oc::sensors::data::Magnetometer::NEW_VAL )
         {
             std::cout << "**** New Magnetometer data ****" << std::endl;
             std::cout << " * Timestamp: " << magData.timestamp << " nsec" << std::endl;
             if(last_mag_ts!=0)
             {
                 std::cout << " * Frequency: " << 1e9/static_cast<float>(magData.timestamp-last_mag_ts) << " Hz" << std::endl;
             }
             last_mag_ts = magData.timestamp;
             std::cout << " * Magnetic field [uT]: " << magData.mX << " " << magData.mY << " " << magData.mZ << std::endl;
         }
         // <---- Get Magnetometer data with a timeout of 100 microseconds to not slow down fastest data (IMU)
         // ----> Get Environment data with a timeout of 100 microseconds to not slow down fastest data (IMU)
         const sl_oc::sensors::data::Environment envData = sens.getLastEnvironmentData(100);
         if( envData.valid == sl_oc::sensors::data::Environment::NEW_VAL )
         {
             std::cout << "**** New Environment data ****" << std::endl;
             std::cout << " * Timestamp: " << envData.timestamp << " nsec" << std::endl;
             if(last_env_ts!=0)
             {
                 std::cout << " * Frequency: " << 1e9/static_cast<float>(envData.timestamp-last_env_ts) << " Hz" << std::endl;
             }
             last_env_ts = envData.timestamp;
             std::cout << " * Pressure [hPa]: " << envData.press << std::endl;
             std::cout << " * Temperature [°C]: " << envData.temp << std::endl;
             std::cout << " * Relative Humidity [%rH]: " << envData.humid << std::endl;
         }
         // <---- Get Environment data with a timeout of 100 microseconds to not slow down fastest data (IMU)
         // ----> Get Temperature data with a timeout of 100 microseconds to not slow down fastest data (IMU)
         const sl_oc::sensors::data::Temperature tempData = sens.getLastCameraTemperatureData(100);
         if( tempData.valid == sl_oc::sensors::data::Temperature::NEW_VAL )
         {
             std::cout << "**** New Camera Sensors Temperature data ****" << std::endl;
             std::cout << " * Timestamp: " << tempData.timestamp << " nsec" << std::endl;
             if(last_cam_temp_ts!=0)
             {
                 std::cout << " * Frequency: " << 1e9/static_cast<float>(tempData.timestamp-last_cam_temp_ts) << " Hz" << std::endl;
             }
             last_cam_temp_ts = tempData.timestamp;
             std::cout << " * Left Camera [°C]: " << tempData.temp_left << std::endl;
             std::cout << " * Right Camera [°C]: " << tempData.temp_right << std::endl;
         }
         // <---- Get Temperature data with a timeout of 100 microseconds to not slow down fastest data (IMU)
     }
     return EXIT_SUCCESS;
 }
References sl_oc::sensors::data::Imu::aX, sl_oc::sensors::data::Imu::aY, sl_oc::sensors::data::Imu::aZ, sl_oc::sensors::SensorCapture::getDeviceList(), sl_oc::sensors::SensorCapture::getFirmwareVersion(), sl_oc::sensors::SensorCapture::getLastCameraTemperatureData(), sl_oc::sensors::SensorCapture::getLastEnvironmentData(), sl_oc::sensors::SensorCapture::getLastIMUData(), sl_oc::sensors::SensorCapture::getLastMagnetometerData(), sl_oc::sensors::SensorCapture::getSerialNumber(), sl_oc::sensors::data::Imu::gX, sl_oc::sensors::data::Imu::gY, sl_oc::sensors::data::Imu::gZ, sl_oc::sensors::data::Environment::humid, sl_oc::INFO, sl_oc::sensors::SensorCapture::initializeSensors(), sl_oc::sensors::data::Magnetometer::mX, sl_oc::sensors::data::Magnetometer::mY, sl_oc::sensors::data::Magnetometer::mZ, sl_oc::sensors::data::Imu::NEW_VAL, sl_oc::sensors::data::Magnetometer::NEW_VAL, sl_oc::sensors::data::Environment::NEW_VAL, sl_oc::sensors::data::Temperature::NEW_VAL, sl_oc::sensors::data::Environment::press, sl_oc::sensors::data::Environment::temp, sl_oc::sensors::data::Temperature::temp_left, sl_oc::sensors::data::Temperature::temp_right, sl_oc::sensors::data::Imu::timestamp, sl_oc::sensors::data::Magnetometer::timestamp, sl_oc::sensors::data::Environment::timestamp, sl_oc::sensors::data::Temperature::timestamp, sl_oc::sensors::data::Imu::valid, sl_oc::sensors::data::Magnetometer::valid, sl_oc::sensors::data::Environment::valid, and sl_oc::sensors::data::Temperature::valid.