ZED Open Capture: zed_oc_rectify_example.cpp File Reference
zed_oc_rectify_example.cpp File Reference
Functions
void showImage (std::string name, cv::Mat &img, sl_oc::video::RESOLUTION res)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Examples
zed_oc_rectify_example.cpp.
Definition at line 39 of file zed_oc_rectify_example.cpp.
{
     sl_oc::VERBOSITY verbose = sl_oc::VERBOSITY::INFO;
     // ----> Set Video parameters
     sl_oc::video::VideoParams params;
     params.res = sl_oc::video::RESOLUTION::HD2K;
     params.fps = sl_oc::video::FPS::FPS_15;
     params.verbose = verbose;
     // <---- Set Video parameters
     // ----> Create Video Capture
     sl_oc::video::VideoCapture cap(params);
     if( !cap.initializeVideo(-1) )
     {
         std::cerr << "Cannot open camera video capture" << std::endl;
         std::cerr << "See verbosity level for more details." << std::endl;
         return EXIT_FAILURE;
     }
     int sn = cap.getSerialNumber();
     std::cout << "Connected to camera sn: " << sn << std::endl;
     // <---- Create Video Capture
     // ----> Retrieve calibration file from Stereolabs server
     std::string calibration_file;
     // ZED Calibration
     unsigned int serial_number = sn;
     // Download camera calibration file
     if( !downloadCalibrationFile(serial_number, calibration_file) )
     {
         std::cerr << "Could not load calibration file from Stereolabs servers" << std::endl;
         return EXIT_FAILURE;
     }
     std::cout << "Calibration file found. Loading..." << std::endl;
     // ----> Frame size
     int w,h;
     cap.getFrameSize(w,h);
     // <---- Frame size
     // ----> Initialize calibration
     cv::Mat map_left_x, map_left_y;
     cv::Mat map_right_x, map_right_y;
     cv::Mat cameraMatrix_left, cameraMatrix_right;
     initCalibration(calibration_file, cv::Size(w/2,h), map_left_x, map_left_y, map_right_x, map_right_y,
                     cameraMatrix_left, cameraMatrix_right);
     std::cout << " Camera Matrix L: \n" << cameraMatrix_left << std::endl << std::endl;
     std::cout << " Camera Matrix R: \n" << cameraMatrix_right << std::endl << std::endl;
     // ----> Initialize calibration
     cv::Mat frameBGR, left_raw, left_rect, right_raw, right_rect;
     uint64_t last_ts=0;
     // Infinite video grabbing loop
     while (1)
     {
         // Get a new frame from camera
         const sl_oc::video::Frame frame = cap.getLastFrame();
         // ----> If the frame is valid we can convert, rectify and display it
         if(frame.data!=nullptr && frame.timestamp!=last_ts)
         {
             last_ts = frame.timestamp;
             // ----> Conversion from YUV 4:2:2 to BGR for visualization
             cv::Mat frameYUV = cv::Mat( frame.height, frame.width, CV_8UC2, frame.data );
             cv::cvtColor(frameYUV,frameBGR,cv::COLOR_YUV2BGR_YUYV);
             // <---- Conversion from YUV 4:2:2 to BGR for visualization
             // ----> Extract left and right images from side-by-sideq
             left_raw = frameBGR(cv::Rect(0, 0, frameBGR.cols / 2, frameBGR.rows));
             right_raw = frameBGR(cv::Rect(frameBGR.cols / 2, 0, frameBGR.cols / 2, frameBGR.rows));
             // Display images
             showImage("left RAW", left_raw, params.res);
             showImage("right RAW", right_raw, params.res);
             // <---- Extract left and right images from side-by-side
             // ----> Apply rectification
             cv::remap(left_raw, left_rect, map_left_x, map_left_y, cv::INTER_LINEAR );
             cv::remap(right_raw, right_rect, map_right_x, map_right_y, cv::INTER_LINEAR );
             showImage("right RECT", right_rect, params.res);
             showImage("left RECT", left_rect, params.res);
             // <---- Apply rectification
         }
         // ----> Keyboard handling
         int key = cv::waitKey( 5 );
         if(key=='q' || key=='Q') // Quit
             break;
         // <---- Keyboard handling
     }
     return EXIT_SUCCESS;
 }
References sl_oc::video::Frame::data, sl_oc::video::VideoParams::fps, sl_oc::video::FPS_15, sl_oc::video::VideoCapture::getFrameSize(), sl_oc::video::VideoCapture::getLastFrame(), sl_oc::video::VideoCapture::getSerialNumber(), sl_oc::video::HD2K, sl_oc::video::Frame::height, sl_oc::INFO, sl_oc::video::VideoCapture::initializeVideo(), sl_oc::video::VideoParams::res, showImage(), sl_oc::video::Frame::timestamp, sl_oc::video::VideoParams::verbose, and sl_oc::video::Frame::width.
showImage()
void showImage (std::string name, cv::Mat & img, sl_oc::video::RESOLUTION res)
Examples
zed_oc_control_example.cpp, and zed_oc_rectify_example.cpp.
Definition at line 139 of file zed_oc_rectify_example.cpp.
 {
     cv::Mat resized;
     switch(res)
     {
     default:
     case sl_oc::video::RESOLUTION::VGA:
         resized = img;
         break;
     case sl_oc::video::RESOLUTION::HD720:
         name += " [Resize factor 0.6]";
         cv::resize( img, resized, cv::Size(), 0.6, 0.6 );
         break;
     case sl_oc::video::RESOLUTION::HD1080:
     case sl_oc::video::RESOLUTION::HD2K:
         name += " [Resize factor 0.4]";
         cv::resize( img, resized, cv::Size(), 0.4, 0.4 );
         break;
     }
     cv::imshow( name, resized );
 }
References sl_oc::video::HD1080, sl_oc::video::HD2K, sl_oc::video::HD720, and sl_oc::video::VGA.
Referenced by main().