ZED Open Capture: sl_oc::tools::SI_ConvertW< SI_CHAR > Class Template Reference
sl_oc::tools::SI_ConvertW< SI_CHAR > Class Template Reference
#include <calibration.hpp>
Public Member Functions
SI_ConvertW (bool a_bStoreIsUtf8)
SI_ConvertW (const SI_ConvertW &rhs)
SI_ConvertW & operator= (const SI_ConvertW &rhs)
size_t SizeFromStore (const char *a_pInputData, size_t a_uInputDataLen)
bool ConvertFromStore (const char *a_pInputData, size_t a_uInputDataLen, SI_CHAR *a_pOutputData, size_t a_uOutputDataSize)
size_t SizeToStore (const SI_CHAR *a_pInputData)
bool ConvertToStore (const SI_CHAR *a_pInputData, char *a_pOutputData, size_t a_uOutputDataSize)
SI_ConvertW (bool a_bStoreIsUtf8)
SI_ConvertW (const SI_ConvertW &rhs)
SI_ConvertW & operator= (const SI_ConvertW &rhs)
~SI_ConvertW ()
size_t SizeFromStore (const char *a_pInputData, size_t a_uInputDataLen)
bool ConvertFromStore (const char *a_pInputData, size_t a_uInputDataLen, UChar *a_pOutputData, size_t a_uOutputDataSize)
size_t SizeToStore (const UChar *a_pInputData)
bool ConvertToStore (const UChar *a_pInputData, char *a_pOutputData, size_t a_uOutputDataSize)
SI_ConvertW (bool a_bStoreIsUtf8)
SI_ConvertW (const SI_ConvertW &rhs)
SI_ConvertW & operator= (const SI_ConvertW &rhs)
size_t SizeFromStore (const char *a_pInputData, size_t a_uInputDataLen)
bool ConvertFromStore (const char *a_pInputData, size_t a_uInputDataLen, SI_CHAR *a_pOutputData, size_t a_uOutputDataSize)
size_t SizeToStore (const SI_CHAR *a_pInputData)
bool ConvertToStore (const SI_CHAR *a_pInputData, char *a_pOutputData, size_t a_uOutputDataSize)
Protected Member Functions
SI_ConvertW ()
SI_ConvertW ()
SI_ConvertW ()
Detailed Description
template<class SI_CHAR>
class sl_oc::tools::SI_ConvertW< SI_CHAR >
Converts UTF-8 to a wchar_t (or equivalent) using the Unicode reference library functions. This can be used on all platforms.
Converts MBCS/UTF-8 to UChar using ICU. This can be used on all platforms.
Converts MBCS and UTF-8 to a wchar_t (or equivalent) on Windows. This uses only the Win32 functions and doesn't require the external Unicode UTF-8 conversion library. It will not work on Windows 95 without using Microsoft Layer for Unicode in your application.
Definition at line 3375 of file calibration.hpp.
Constructor & Destructor Documentation
SI_ConvertW() [1/9]
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW () inline protected
Definition at line 3379 of file calibration.hpp.
                   {
     }
SI_ConvertW() [2/9]
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW (bool a_bStoreIsUtf8) inline
Definition at line 3383 of file calibration.hpp.
                                      : m_bStoreIsUtf8(a_bStoreIsUtf8) {
     }
SI_ConvertW() [3/9]
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW (const SI_ConvertW< SI_CHAR > & rhs) inline
Definition at line 3387 of file calibration.hpp.
{
         operator=(rhs);
     }
References sl_oc::tools::SI_ConvertW< SI_CHAR >::operator=().
SI_ConvertW() [4/9]
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW () inline protected
Definition at line 3585 of file calibration.hpp.
                   : m_pEncoding(NULL), m_pConverter(NULL) {
     }
SI_ConvertW() [5/9]
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW (bool a_bStoreIsUtf8) inline
Definition at line 3589 of file calibration.hpp.
                                      : m_pConverter(NULL) {
         m_pEncoding = a_bStoreIsUtf8 ? "UTF-8" : NULL;
     }
SI_ConvertW() [6/9]
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW (const SI_ConvertW< SI_CHAR > & rhs) inline
Definition at line 3594 of file calibration.hpp.
{
         operator=(rhs);
     }
References sl_oc::tools::SI_ConvertW< SI_CHAR >::operator=().
~SI_ConvertW()
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::~SI_ConvertW () inline
Definition at line 3604 of file calibration.hpp.
                    {
         if (m_pConverter) ucnv_close(m_pConverter);
     }
SI_ConvertW() [7/9]
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW () inline protected
Definition at line 3815 of file calibration.hpp.
                   {
     }
SI_ConvertW() [8/9]
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW (bool a_bStoreIsUtf8) inline
Definition at line 3819 of file calibration.hpp.
{
         m_uCodePage = a_bStoreIsUtf8 ? CP_UTF8 : CP_ACP;
     }
SI_ConvertW() [9/9]
template<class SI_CHAR > sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW (const SI_ConvertW< SI_CHAR > & rhs) inline
Definition at line 3824 of file calibration.hpp.
{
         operator=(rhs);
     }
References sl_oc::tools::SI_ConvertW< SI_CHAR >::operator=().
Member Function Documentation
ConvertFromStore() [1/3]
template<class SI_CHAR > bool sl_oc::tools::SI_ConvertW< SI_CHAR >::ConvertFromStore (const char * a_pInputData, size_t a_uInputDataLen, SI_CHAR * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string from the storage format to SI_CHAR. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to SI_CHAR.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
a_pOutputData Pointer to the output buffer to received the converted data.
a_uOutputDataSize Size of the output buffer in SI_CHAR.
Returns
true if all of the input data was successfully converted.
Definition at line 3445 of file calibration.hpp.
{
         if (m_bStoreIsUtf8) {
             // This uses the Unicode reference implementation to do the
             // conversion from UTF-8 to wchar_t. The required files are
             // ConvertUTF.h and ConvertUTF.c which should be included in
             // the distribution but are publically available from unicode.org
             // at http://www.unicode.org/Public/PROGRAMS/CVTUTF/
             ConversionResult retval;
             const UTF8 * pUtf8 = (const UTF8 *) a_pInputData;
             if (sizeof (wchar_t) == sizeof (UTF32)) {
                 UTF32 * pUtf32 = (UTF32 *) a_pOutputData;
                 retval = ConvertUTF8toUTF32(
                         &pUtf8, pUtf8 + a_uInputDataLen,
                         &pUtf32, pUtf32 + a_uOutputDataSize,
                         lenientConversion);
             } else if (sizeof (wchar_t) == sizeof (UTF16)) {
                 UTF16 * pUtf16 = (UTF16 *) a_pOutputData;
                 retval = ConvertUTF8toUTF16(
                         &pUtf8, pUtf8 + a_uInputDataLen,
                         &pUtf16, pUtf16 + a_uOutputDataSize,
                         lenientConversion);
             }
             return retval == conversionOK;
         }
         // convert to wchar_t
         size_t retval = mbstowcs(a_pOutputData,
                 a_pInputData, a_uOutputDataSize);
         return retval != (size_t) (-1);
     }
References sl_oc::tools::conversionOK, sl_oc::tools::ConvertUTF8toUTF16(), sl_oc::tools::ConvertUTF8toUTF32(), and sl_oc::tools::lenientConversion.
ConvertFromStore() [2/3]
template<class SI_CHAR > bool sl_oc::tools::SI_ConvertW< SI_CHAR >::ConvertFromStore (const char * a_pInputData, size_t a_uInputDataLen, SI_CHAR * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string from the storage format to SI_CHAR. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to SI_CHAR.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
a_pOutputData Pointer to the output buffer to received the converted data.
a_uOutputDataSize Size of the output buffer in SI_CHAR.
Returns
true if all of the input data was successfully converted.
Definition at line 3871 of file calibration.hpp.
{
         int nSize = MultiByteToWideChar(
                 m_uCodePage, 0,
                 a_pInputData, (int) a_uInputDataLen,
                 (wchar_t *) a_pOutputData, (int) a_uOutputDataSize);
         return (nSize > 0);
     }
ConvertFromStore() [3/3]
template<class SI_CHAR > bool sl_oc::tools::SI_ConvertW< SI_CHAR >::ConvertFromStore (const char * a_pInputData, size_t a_uInputDataLen, UChar * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string from the storage format to UChar. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to UChar.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
a_pOutputData Pointer to the output buffer to received the converted data.
a_uOutputDataSize Size of the output buffer in UChar.
Returns
true if all of the input data was successfully converted.
Definition at line 3659 of file calibration.hpp.
{
         UErrorCode nError;
         if (!m_pConverter) {
             nError = U_ZERO_ERROR;
             m_pConverter = ucnv_open(m_pEncoding, &nError);
             if (U_FAILURE(nError)) {
                 return false;
             }
         }
         nError = U_ZERO_ERROR;
         ucnv_toUChars(m_pConverter,
                 a_pOutputData, (int32_t) a_uOutputDataSize,
                 a_pInputData, (int32_t) a_uInputDataLen, &nError);
         if (U_FAILURE(nError)) {
             return false;
         }
         return true;
     }
ConvertToStore() [1/3]
template<class SI_CHAR > bool sl_oc::tools::SI_ConvertW< SI_CHAR >::ConvertToStore (const SI_CHAR * a_pInputData, char * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string to the storage format of this data. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData NULL terminated source string to convert. All of the data will be converted including the terminating NULL character.
a_pOutputData Pointer to the buffer to receive the converted string.
a_uOutputDataSize Size of the output buffer in char.
Returns
true if all of the input data, including the terminating NULL character was successfully converted.
Definition at line 3521 of file calibration.hpp.
               {
         if (m_bStoreIsUtf8) {
             // calc input string length (SI_CHAR type and size independent)
             size_t uInputLen = 0;
             while (a_pInputData[uInputLen]) {
                 ++uInputLen;
             }
             ++uInputLen; // include the NULL char
             // This uses the Unicode reference implementation to do the
             // conversion from wchar_t to UTF-8. The required files are
             // ConvertUTF.h and ConvertUTF.c which should be included in
             // the distribution but are publically available from unicode.org
             // at http://www.unicode.org/Public/PROGRAMS/CVTUTF/
             ConversionResult retval;
             UTF8 * pUtf8 = (UTF8 *) a_pOutputData;
             if (sizeof (wchar_t) == sizeof (UTF32)) {
                 const UTF32 * pUtf32 = (const UTF32 *) a_pInputData;
                 retval = ConvertUTF32toUTF8(
                         &pUtf32, pUtf32 + uInputLen,
                         &pUtf8, pUtf8 + a_uOutputDataSize,
                         lenientConversion);
             } else if (sizeof (wchar_t) == sizeof (UTF16)) {
                 const UTF16 * pUtf16 = (const UTF16 *) a_pInputData;
                 retval = ConvertUTF16toUTF8(
                         &pUtf16, pUtf16 + uInputLen,
                         &pUtf8, pUtf8 + a_uOutputDataSize,
                         lenientConversion);
             }
             return retval == conversionOK;
         } else {
             size_t retval = wcstombs(a_pOutputData,
                     a_pInputData, a_uOutputDataSize);
             return retval != (size_t) - 1;
         }
     }
References sl_oc::tools::conversionOK, sl_oc::tools::ConvertUTF16toUTF8(), sl_oc::tools::ConvertUTF32toUTF8(), and sl_oc::tools::lenientConversion.
ConvertToStore() [2/3]
template<class SI_CHAR > bool sl_oc::tools::SI_ConvertW< SI_CHAR >::ConvertToStore (const SI_CHAR * a_pInputData, char * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string to the storage format of this data. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData NULL terminated source string to convert. All of the data will be converted including the terminating NULL character.
a_pOutputData Pointer to the buffer to receive the converted string.
a_uOutputDataSize Size of the output buffer in char.
Returns
true if all of the input data, including the terminating NULL character was successfully converted.
Definition at line 3915 of file calibration.hpp.
{
         int retval = WideCharToMultiByte(
                 m_uCodePage, 0,
                 (const wchar_t *) a_pInputData, -1,
                 a_pOutputData, (int) a_uOutputDataSize, 0, 0);
         return retval > 0;
     }
ConvertToStore() [3/3]
template<class SI_CHAR > bool sl_oc::tools::SI_ConvertW< SI_CHAR >::ConvertToStore (const UChar * a_pInputData, char * a_pOutputData, size_t a_uOutputDataSize) inline
Convert the input string to the storage format of this data. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData NULL terminated source string to convert. All of the data will be converted including the terminating NULL character.
a_pOutputData Pointer to the buffer to receive the converted string.
a_uOutputDataSize Size of the output buffer in char.
Returns
true if all of the input data, including the terminating NULL character was successfully converted.
Definition at line 3730 of file calibration.hpp.
{
         UErrorCode nError;
         if (!m_pConverter) {
             nError = U_ZERO_ERROR;
             m_pConverter = ucnv_open(m_pEncoding, &nError);
             if (U_FAILURE(nError)) {
                 return false;
             }
         }
         nError = U_ZERO_ERROR;
         ucnv_fromUChars(m_pConverter,
                 a_pOutputData, (int32_t) a_uOutputDataSize,
                 a_pInputData, -1, &nError);
         if (U_FAILURE(nError)) {
             return false;
         }
         return true;
     }
operator=() [1/3]
template<class SI_CHAR > SI_ConvertW& sl_oc::tools::SI_ConvertW< SI_CHAR >::operator= (const SI_ConvertW< SI_CHAR > & rhs) inline
Definition at line 3391 of file calibration.hpp.
{
         m_bStoreIsUtf8 = rhs.m_bStoreIsUtf8;
         return *this;
     }
Referenced by sl_oc::tools::SI_ConvertW< SI_CHAR >::SI_ConvertW().
operator=() [2/3]
template<class SI_CHAR > SI_ConvertW& sl_oc::tools::SI_ConvertW< SI_CHAR >::operator= (const SI_ConvertW< SI_CHAR > & rhs) inline
Definition at line 3598 of file calibration.hpp.
{
         m_pEncoding = rhs.m_pEncoding;
         m_pConverter = NULL;
         return *this;
     }
operator=() [3/3]
template<class SI_CHAR > SI_ConvertW& sl_oc::tools::SI_ConvertW< SI_CHAR >::operator= (const SI_ConvertW< SI_CHAR > & rhs) inline
Definition at line 3828 of file calibration.hpp.
{
         m_uCodePage = rhs.m_uCodePage;
         return *this;
     }
SizeFromStore() [1/3]
template<class SI_CHAR > size_t sl_oc::tools::SI_ConvertW< SI_CHAR >::SizeFromStore (const char * a_pInputData, size_t a_uInputDataLen) inline
Calculate the number of SI_CHAR required for converting the input from the storage format. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to SI_CHAR.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
Returns
Number of SI_CHAR required by the string when converted. If there are embedded NULL bytes in the input data, only the string up and not including the NULL byte will be converted.
-1 cast to size_t on a conversion error.
Definition at line 3409 of file calibration.hpp.
{
         SI_ASSERT(a_uInputDataLen != (size_t) - 1);
         if (m_bStoreIsUtf8) {
             // worst case scenario for UTF-8 to wchar_t is 1 char -> 1 wchar_t
             // so we just return the same number of characters required as for
             // the source text.
             return a_uInputDataLen;
         }
 #if defined(SI_NO_MBSTOWCS_NULL) || (!defined(_MSC_VER) && !defined(_linux))
         // fall back processing for platforms that don't support a NULL dest to mbstowcs
         // worst case scenario is 1:1, this will be a sufficient buffer size
         (void) a_pInputData;
         return a_uInputDataLen;
 #else
         // get the actual required buffer size
         return mbstowcs(NULL, a_pInputData, a_uInputDataLen);
 #endif
     }
SizeFromStore() [2/3]
template<class SI_CHAR > size_t sl_oc::tools::SI_ConvertW< SI_CHAR >::SizeFromStore (const char * a_pInputData, size_t a_uInputDataLen) inline
Calculate the number of UChar required for converting the input from the storage format. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to UChar.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
Returns
Number of UChar required by the string when converted. If there are embedded NULL bytes in the input data, only the string up and not including the NULL byte will be converted.
-1 cast to size_t on a conversion error.
Definition at line 3621 of file calibration.hpp.
{
         SI_ASSERT(a_uInputDataLen != (size_t) - 1);
         UErrorCode nError;
         if (!m_pConverter) {
             nError = U_ZERO_ERROR;
             m_pConverter = ucnv_open(m_pEncoding, &nError);
             if (U_FAILURE(nError)) {
                 return (size_t) - 1;
             }
         }
         nError = U_ZERO_ERROR;
         int32_t nLen = ucnv_toUChars(m_pConverter, NULL, 0,
                 a_pInputData, (int32_t) a_uInputDataLen, &nError);
         if (U_FAILURE(nError) && nError != U_BUFFER_OVERFLOW_ERROR) {
             return (size_t) - 1;
         }
         return (size_t) nLen;
     }
SizeFromStore() [3/3]
template<class SI_CHAR > size_t sl_oc::tools::SI_ConvertW< SI_CHAR >::SizeFromStore (const char * a_pInputData, size_t a_uInputDataLen) inline
Calculate the number of SI_CHAR required for converting the input from the storage format. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData Data in storage format to be converted to SI_CHAR.
a_uInputDataLen Length of storage format data in bytes. This must be the actual length of the data, including NULL byte if NULL terminated string is required.
Returns
Number of SI_CHAR required by the string when converted. If there are embedded NULL bytes in the input data, only the string up and not including the NULL byte will be converted.
-1 cast to size_t on a conversion error.
Definition at line 3846 of file calibration.hpp.
{
         SI_ASSERT(a_uInputDataLen != (size_t) - 1);
         int retval = MultiByteToWideChar(
                 m_uCodePage, 0,
                 a_pInputData, (int) a_uInputDataLen,
                 0, 0);
         return (size_t) (retval > 0 ? retval : -1);
     }
SizeToStore() [1/3]
template<class SI_CHAR > size_t sl_oc::tools::SI_ConvertW< SI_CHAR >::SizeToStore (const SI_CHAR * a_pInputData) inline
Calculate the number of char required by the storage format of this data. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData NULL terminated string to calculate the number of bytes required to be converted to storage format.
Returns
Number of bytes required by the string when converted to storage format. This size always includes space for the terminating NULL character.
-1 cast to size_t on a conversion error.
Definition at line 3490 of file calibration.hpp.
{
         if (m_bStoreIsUtf8) {
             // worst case scenario for wchar_t to UTF-8 is 1 wchar_t -> 6 char
             size_t uLen = 0;
             while (a_pInputData[uLen]) {
                 ++uLen;
             }
             return (6 * uLen) + 1;
         } else {
             size_t uLen = wcstombs(NULL, a_pInputData, 0);
             if (uLen == (size_t) (-1)) {
                 return uLen;
             }
             return uLen + 1; // include NULL terminator
         }
     }
SizeToStore() [2/3]
template<class SI_CHAR > size_t sl_oc::tools::SI_ConvertW< SI_CHAR >::SizeToStore (const SI_CHAR * a_pInputData) inline
Calculate the number of char required by the storage format of this data. The storage format is always UTF-8.
Parameters
a_pInputData NULL terminated string to calculate the number of bytes required to be converted to storage format.
Returns
Number of bytes required by the string when converted to storage format. This size always includes space for the terminating NULL character.
-1 cast to size_t on a conversion error.
Definition at line 3893 of file calibration.hpp.
{
         int retval = WideCharToMultiByte(
                 m_uCodePage, 0,
                 (const wchar_t *) a_pInputData, -1,
                 0, 0, 0, 0);
         return (size_t) (retval > 0 ? retval : -1);
     }
SizeToStore() [3/3]
template<class SI_CHAR > size_t sl_oc::tools::SI_ConvertW< SI_CHAR >::SizeToStore (const UChar * a_pInputData) inline
Calculate the number of char required by the storage format of this data. The storage format is always UTF-8 or MBCS.
Parameters
a_pInputData NULL terminated string to calculate the number of bytes required to be converted to storage format.
Returns
Number of bytes required by the string when converted to storage format. This size always includes space for the terminating NULL character.
-1 cast to size_t on a conversion error.
Definition at line 3695 of file calibration.hpp.
{
         UErrorCode nError;
         if (!m_pConverter) {
             nError = U_ZERO_ERROR;
             m_pConverter = ucnv_open(m_pEncoding, &nError);
             if (U_FAILURE(nError)) {
                 return (size_t) - 1;
             }
         }
         nError = U_ZERO_ERROR;
         int32_t nLen = ucnv_fromUChars(m_pConverter, NULL, 0,
                 a_pInputData, -1, &nError);
         if (U_FAILURE(nError) && nError != U_BUFFER_OVERFLOW_ERROR) {
             return (size_t) - 1;
         }
         return (size_t) nLen + 1;
     }
The documentation for this class was generated from the following file:
calibration.hpp