ZED Open Capture: sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter Class Reference
sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter Class Reference
#include <calibration.hpp>
Public Member Functions
Converter (bool a_bStoreIsUtf8)
Converter (const Converter &rhs)
Converter & operator= (const Converter &rhs)
bool ConvertToStore (const SI_CHAR *a_pszString)
const char * Data ()
Detailed Description
template<class SI_CHAR, class SI_STRLESS, class SI_CONVERTER>
class sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter
Characterset conversion utility class to convert strings to the same format as is used for the storage.
Definition at line 275 of file calibration.hpp.
Constructor & Destructor Documentation
Converter() [1/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter (bool a_bStoreIsUtf8) inline
Definition at line 278 of file calibration.hpp.
                                        : SI_CONVERTER(a_bStoreIsUtf8) {
             m_scratch.resize(1024);
         }
Converter() [2/2]
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter (const Converter & rhs) inline
Definition at line 282 of file calibration.hpp.
{
             operator=(rhs);
         }
References sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::operator=().
Member Function Documentation
ConvertToStore()
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > bool sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::ConvertToStore (const SI_CHAR * a_pszString) inline
Definition at line 291 of file calibration.hpp.
{
             size_t uLen = SI_CONVERTER::SizeToStore(a_pszString);
             if (uLen == (size_t) (-1)) {
                 return false;
             }
             while (uLen > m_scratch.size()) {
                 m_scratch.resize(m_scratch.size() * 2);
             }
             return SI_CONVERTER::ConvertToStore(
                     a_pszString,
                     const_cast<char*> (m_scratch.data()),
                     m_scratch.size());
         }
Referenced by sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save().
Data()
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > const char* sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Data () inline
Definition at line 305 of file calibration.hpp.
{
             return m_scratch.data();
         }
Referenced by sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Save().
operator=()
template<class SI_CHAR , class SI_STRLESS , class SI_CONVERTER > Converter& sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::operator= (const Converter & rhs) inline
Definition at line 286 of file calibration.hpp.
{
             m_scratch = rhs.m_scratch;
             return *this;
         }
Referenced by sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::Converter::Converter().
The documentation for this class was generated from the following file:
calibration.hpp