ZED Open Capture: sl_oc::tools::ConfManager Class Reference
sl_oc::tools::ConfManager Class Reference
#include <calibration.hpp>
Public Member Functions
ConfManager (std::string filename)
~ConfManager ()
float getValue (std::string key, float default_value=-1)
void setValue (std::string key, float value)
bool isOpened ()
Detailed Description
Definition at line 4003 of file calibration.hpp.
Constructor & Destructor Documentation
ConfManager()
sl_oc::tools::ConfManager::ConfManager (std::string filename) inline
Definition at line 4006 of file calibration.hpp.
{
         filename_ = filename;
         ini_.SetUnicode();
         SI_Error rc = ini_.LoadFile(filename_.c_str());
         is_opened_ = !(rc < 0);
     }
References sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadFile(), and sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetUnicode().
~ConfManager()
sl_oc::tools::ConfManager::~ConfManager () inline
Definition at line 4013 of file calibration.hpp.
                    {
         //if (is_opened_) ini_.SaveFile(filename_.c_str());
     }
Member Function Documentation
getValue()
float sl_oc::tools::ConfManager::getValue (std::string key, float default_value = -1) inline
Definition at line 4017 of file calibration.hpp.
{
         if (is_opened_) {
             std::vector<std::string> elems;
             split(key, ':', elems);
             return atof(ini_.GetValue(elems.front().c_str(), elems.back().c_str(), std::to_string(default_value).c_str()));
         } else
             return -1.f;
     }
References sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetValue(), and sl_oc::tools::split().
Referenced by sl_oc::tools::initCalibration().
isOpened()
bool sl_oc::tools::ConfManager::isOpened () inline
Definition at line 4036 of file calibration.hpp.
{
         return is_opened_;
     }
Referenced by sl_oc::tools::initCalibration().
setValue()
void sl_oc::tools::ConfManager::setValue (std::string key, float value) inline
Definition at line 4027 of file calibration.hpp.
{
         if (is_opened_) {
             std::vector<std::string> elems;
             split(key, ':', elems);
             /*SI_Error rc = */ini_.SetValue(elems.front().c_str(), elems.back().c_str(), std::to_string(value).c_str());
         }
     }
References sl_oc::tools::CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetValue(), and sl_oc::tools::split().
The documentation for this class was generated from the following file:
calibration.hpp