ZED Open Capture: sl_oc::tools::StopWatch Class Reference
sl_oc::tools::StopWatch Class Reference
Stop Timer used to measure time intervals.
#include <stopwatch.hpp>
Public Member Functions
StopWatch ()
StopWatch constructor. Automatically starts time measurement.
virtual ~StopWatch ()
void tic ()
Set the beginning time of the time measurement.
double toc ()
Calculates the seconds elapsed from the last tic.
Detailed Description
Stop Timer used to measure time intervals.
Examples
zed_oc_depth_example.cpp, and zed_oc_tune_stereo_sgbm.cpp.
Definition at line 33 of file stopwatch.hpp.
Constructor & Destructor Documentation
StopWatch()
sl_oc::tools::StopWatch::StopWatch () inline
StopWatch constructor. Automatically starts time measurement.
Definition at line 40 of file stopwatch.hpp.
 {tic();}
References tic().
~StopWatch()
virtual sl_oc::tools::StopWatch::~StopWatch () inline virtual
Definition at line 41 of file stopwatch.hpp.
 {};
Member Function Documentation
tic()
void sl_oc::tools::StopWatch::tic () inline
Set the beginning time of the time measurement.
Definition at line 46 of file stopwatch.hpp.
     {
         mStartTime = std::chrono::steady_clock::now(); // Set the start time point
     }
Referenced by StopWatch().
toc()
double sl_oc::tools::StopWatch::toc () inline
Calculates the seconds elapsed from the last tic.
Returns
the seconds elapsed from the last tic with microseconds resolution.
Examples
zed_oc_depth_example.cpp, and zed_oc_tune_stereo_sgbm.cpp.
Definition at line 55 of file stopwatch.hpp.
     {
         auto now = std::chrono::steady_clock::now();
         double elapsed_usec = std::chrono::duration_cast<std::chrono::microseconds>(now - mStartTime).count();
         return elapsed_usec/1e6;
     }
Referenced by applyStereoMatching(), and main().
The documentation for this class was generated from the following file:
stopwatch.hpp