ZED Open Capture: ConfManager Class Reference
ConfManager Class Reference
#include <calibration.hpp>
Public Member Functions
ConfManager (std::string filename)
~ConfManager ()
float getValue (std::string key, float default_value=-1)
void setValue (std::string key, float value)
bool isOpened ()
Detailed Description
Definition at line 4010 of file calibration.hpp.
Constructor & Destructor Documentation
ConfManager()
ConfManager::ConfManager (std::string filename) inline
Definition at line 4013 of file calibration.hpp.
{
         filename_ = filename;
         ini_.SetUnicode();
         SI_Error rc = ini_.LoadFile(filename_.c_str());
         is_opened_ = !(rc < 0);
     }
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::LoadFile(), and CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetUnicode().
~ConfManager()
ConfManager::~ConfManager () inline
Definition at line 4020 of file calibration.hpp.
                    {
         //if (is_opened_) ini_.SaveFile(filename_.c_str());
     }
Member Function Documentation
getValue()
float ConfManager::getValue (std::string key, float default_value = -1) inline
Definition at line 4024 of file calibration.hpp.
{
         if (is_opened_) {
             std::vector<std::string> elems;
             split(key, ':', elems);
             return atof(ini_.GetValue(elems.front().c_str(), elems.back().c_str(), std::to_string(default_value).c_str()));
         } else
             return -1.f;
     }
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::GetValue(), and split().
Referenced by initCalibration().
isOpened()
bool ConfManager::isOpened () inline
Definition at line 4043 of file calibration.hpp.
{
         return is_opened_;
     }
Referenced by initCalibration().
setValue()
void ConfManager::setValue (std::string key, float value) inline
Definition at line 4034 of file calibration.hpp.
{
         if (is_opened_) {
             std::vector<std::string> elems;
             split(key, ':', elems);
             /*SI_Error rc = */ini_.SetValue(elems.front().c_str(), elems.back().c_str(), std::to_string(value).c_str());
         }
     }
References CSimpleIniTempl< SI_CHAR, SI_STRLESS, SI_CONVERTER >::SetValue(), and split().
The documentation for this class was generated from the following file:
calibration.hpp